export interface CareerData {
  id: string;
  slug: string;
  nameUz: string;
  nameKrill: string;
  nameRu: string;
  nameEn: string;
  category: string;
  imageUrl: string;
  descriptionUz: string;
  descriptionKrill: string;
  descriptionRu: string;
  descriptionEn: string;
  skills: string[];
  subjects: string[];
  learningPath: {
    stage1: { period: string; title: string; items: string[] };
    stage2: { period: string; title: string; items: string[] };
    stage3: { period: string; title: string; items: string[] };
    stage4: { period: string; title: string; items: string[] };
  };
  educationPath: string;
  futureOutlook: string;
  relatedCareers: string[];
  weightTech: number;
  weightMed: number;
  weightEng: number;
  weightSoc: number;
  weightCre: number;
  weightBus: number;
  weightNat: number;
  weightLaw: number;
  active: boolean;
}

export interface QuestionData {
  id: string;
  orderNumber: number;
  questionUz: string;
  questionKrill: string;
  questionRu: string;
  questionEn: string;
  category: string;
  active: boolean;
  weightTech: number;
  weightMed: number;
  weightEng: number;
  weightSoc: number;
  weightCre: number;
  weightBus: number;
  weightNat: number;
  weightLaw: number;
  correlatedSubject?: string;
  correlatedTrait?: string;
  isPressureCheck?: boolean;
}

export const SEED_QUESTIONS: QuestionData[] = [
  // 1-8: Technology & Computing
  {
    id: "q-1",
    orderNumber: 1,
    questionUz: "Kompyuterda yoki telefonda biror dastur ishlamay qolsa, uning nima sababdan buzilganini aniqlashga qiziqaman.",
    questionKrill: "Компьютерда ёки телефонда бирор дастур ишламай қолса, унинг нима сабабдан бузилганини аниқлашга қизиқаман.",
    questionRu: "Если на компьютере или телефоне зависает программа, мне интересно выяснить причину сбоя.",
    questionEn: "When an app or computer glitches, I enjoy digging in to understand the root cause.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 9.5,
    weightMed: 0,
    weightEng: 4.0,
    weightSoc: 0,
    weightCre: 2.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 1.0,
    correlatedSubject: "Informatika",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-2",
    orderNumber: 2,
    questionUz: "Dasturlash tillarini (masalan, Python, C++, JavaScript) o‘rganish va kod yozish jarayoni meni o‘ziga jalb qiladi.",
    questionKrill: "Дастурлаш тилларини (масалан, Python, C++, JavaScript) ўрганиш ва код ёзиш жараёни мени ўзига жалб қилади.",
    questionRu: "Изучение языков программирования и написание собственного кода вызывает у меня живой интерес.",
    questionEn: "Learning coding languages and writing programs genuinely excites me.",
    category: "SUBJECT",
    active: true,
    weightTech: 10.0,
    weightMed: 0,
    weightEng: 5.0,
    weightSoc: 0,
    weightCre: 3.0,
    weightBus: 2.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Informatika",
    correlatedTrait: "Technical thinking"
  },
  {
    id: "q-3",
    orderNumber: 3,
    questionUz: "Murakkab matematik hisob-kitoblar, tenglamalar va mantiqiy jumboqlarni yechish menga yoqadi.",
    questionKrill: "Мураккаб математик ҳисоб-китоблар, тенгламалар ва мантиқий жумбоқларни ечиш менга ёқади.",
    questionRu: "Мне нравится решать сложные математические задачи, уравнения и логические головоломки.",
    questionEn: "I take satisfaction in solving challenging math problems, formulas, and logic puzzles.",
    category: "SUBJECT",
    active: true,
    weightTech: 7.0,
    weightMed: 2.0,
    weightEng: 8.0,
    weightSoc: 0,
    weightCre: 1.0,
    weightBus: 6.0,
    weightNat: 0,
    weightLaw: 1.0,
    correlatedSubject: "Matematika",
    correlatedTrait: "Technical thinking"
  },
  {
    id: "q-4",
    orderNumber: 4,
    questionUz: "Internet tarmoqlari, sun’iy intellekt (AI) va zamonaviy raqamli xavfsizlik tizimlari qanday ishlashini bilishni xohlayman.",
    questionKrill: "Интернет тармоқлари, сунъий интеллект (AI) ва замонавий рақамли хавфсизлик тизимлари қандай ишлашини билишни хоҳлайман.",
    questionRu: "Я хочу глубже понять, как функционируют интернет-сети, искусственный интеллект и кибербезопасность.",
    questionEn: "I want to explore how computer networks, artificial intelligence, and cybersecurity function.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 9.0,
    weightMed: 0,
    weightEng: 6.0,
    weightSoc: 1.0,
    weightCre: 2.0,
    weightBus: 3.0,
    weightNat: 0,
    weightLaw: 4.0,
    correlatedSubject: "Informatika",
    correlatedTrait: "Technical thinking"
  },

  // 5-9: Engineering, Robotics & Construction
  {
    id: "q-5",
    orderNumber: 5,
    questionUz: "Buzilgan maishiy texnika yoki mexanizmlarni ochib, uning ichki qismlarini ko‘rish va tuzatish meni qiziqtiradi.",
    questionKrill: "Бузилган маиший техника ёки механизмларни очиб, унинг ички қисмларини кўриш ва тузатиш мени қизиқтиради.",
    questionRu: "Мне интересно разбирать сломанные приборы, изучать их внутренности и пробовать чинить.",
    questionEn: "I like taking broken appliances or mechanisms apart to understand their gears and fix them.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 4.0,
    weightMed: 0,
    weightEng: 10.0,
    weightSoc: 0,
    weightCre: 2.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Fizika",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-6",
    orderNumber: 6,
    questionUz: "Robotlar yasash, mikrosxemalar ulash yoki turli elektron datchiklar bilan tajribalar o‘tkazishni yoqtiraman.",
    questionKrill: "Роботлар ясаш, микросхемалар улаш ёки турли электрон датчиклар билан тажрибалар ўтказишни ёқтираман.",
    questionRu: "Мне нравится собирать роботов, соединять микросхемы и паять электронные датчики.",
    questionEn: "Building robots, soldering circuits, or experimenting with electronic sensors excites me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 7.0,
    weightMed: 0,
    weightEng: 9.5,
    weightSoc: 0,
    weightCre: 4.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Fizika",
    correlatedTrait: "Technical thinking"
  },
  {
    id: "q-7",
    orderNumber: 7,
    questionUz: "Yangi binolar, ko‘priklar, chiroyli inshootlar loyihasini chizish va 3D modellash bilan shug‘ullanishni xohlardim.",
    questionKrill: "Янги бинолар, кўприклар, чиройли иншоотлар лойиҳасини чизиш ва 3D моделлаш билан шуғулланишни хоҳлардим.",
    questionRu: "Я хотел бы проектировать современные здания, мосты и заниматься их 3D-моделированием.",
    questionEn: "I would enjoy drafting architectural designs for buildings and bridges using 3D modeling.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 4.0,
    weightMed: 0,
    weightEng: 8.5,
    weightSoc: 0,
    weightCre: 7.0,
    weightBus: 2.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Chizmachilik",
    correlatedTrait: "Creativity"
  },
  {
    id: "q-8",
    orderNumber: 8,
    questionUz: "Qurilish, mebelsozlik yoki turli xomashyolardan yangi foydali buyumlar yasashda qo‘l mehnati bilan ishlash yoqadi.",
    questionKrill: "Қурилиш, мебелсозлик ёки турли хомашёлардан янги фойдали буюмлар ясашда қўл меҳнати билан ишлаш ёқади.",
    questionRu: "Мне приятно работать руками: конструировать мебель, строить или создавать полезные изделия.",
    questionEn: "I enjoy hands-on crafting, woodwork, construction, or shaping raw materials into products.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 1.0,
    weightMed: 0,
    weightEng: 8.0,
    weightSoc: 0,
    weightCre: 4.0,
    weightBus: 2.0,
    weightNat: 1.0,
    weightLaw: 0,
    correlatedSubject: "Mehnat",
    correlatedTrait: "Practical work"
  },

  // 9-14: Medical & Healthcare
  {
    id: "q-9",
    orderNumber: 9,
    questionUz: "Inson tanasining anatomiyasi, yurak, asab tizimi va a’zolarning qanday ishlashi meni doimo qiziqtiradi.",
    questionKrill: "Инсон танасининг анатомияси, юрак, асаб тизими ва аъзоларнинг қандай ишлаши мени доимо қизиқтиради.",
    questionRu: "Меня всегда интересовало устройство человеческого тела: анатомия, работа сердца и нервной системы.",
    questionEn: "Human anatomy, how internal organs function, and the nervous system always captivate me.",
    category: "SUBJECT",
    active: true,
    weightTech: 1.0,
    weightMed: 10.0,
    weightEng: 0,
    weightSoc: 4.0,
    weightCre: 0,
    weightBus: 0,
    weightNat: 4.0,
    weightLaw: 0,
    correlatedSubject: "Biologiya",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-10",
    orderNumber: 10,
    questionUz: "Bemor yoki jarohatlangan insonga birinchi tibbiy yordam ko‘rsatish, dori-darmonlar tarkibini o‘rganishdan qo‘rqmayman.",
    questionKrill: "Бемор ёки жароҳатланган инсонга биринчи тиббий ёрдам кўрсатиш, дори-дармонлар таркибини ўрганишдан қўрқмайман.",
    questionRu: "Я не боюсь оказывать первую помощь пострадавшим и с интересом изучаю состав медикаментов.",
    questionEn: "I am not squeamish about providing first aid to injured people and exploring medicines.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 9.5,
    weightEng: 0,
    weightSoc: 6.0,
    weightCre: 0,
    weightBus: 0,
    weightNat: 2.0,
    weightLaw: 0,
    correlatedSubject: "Biologiya",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-11",
    orderNumber: 11,
    questionUz: "Kimyoviy moddalarni aralashtirib tajriba o‘tkazish, mikroskop ostida bakteriya va hujayralarni tekshirish qiziq.",
    questionKrill: "Кимёвий моддаларни аралаштириб тажриба ўтказиш, микроскоп остида бактерия ва ҳужайраларни текшириш қизиқ.",
    questionRu: "Мне нравится проводить опыты в химической лаборатории и рассматривать клетки под микроскопом.",
    questionEn: "Conducting chemistry lab experiments and examining cells under a microscope excites me.",
    category: "SUBJECT",
    active: true,
    weightTech: 2.0,
    weightMed: 8.5,
    weightEng: 2.0,
    weightSoc: 0,
    weightCre: 1.0,
    weightBus: 0,
    weightNat: 7.0,
    weightLaw: 0,
    correlatedSubject: "Kimyo",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-12",
    orderNumber: 12,
    questionUz: "Insonlarning ruhiy holati, tushkunlik sabablari va ularning kayfiyatini ko‘tarish yo‘llarini tushunishga intilaman.",
    questionKrill: "Инсонларнинг руҳий ҳолати, тушкунлик сабаблари ва уларнинг кайфиятини кўтариш йўлларини тушунишга интиламан.",
    questionRu: "Я стремлюсь понимать психологию людей, причины переживаний и способы эмоциональной поддержки.",
    questionEn: "I am drawn to understanding human psychology, emotional struggles, and methods to uplift people.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 7.0,
    weightEng: 0,
    weightSoc: 9.0,
    weightCre: 2.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 1.0,
    correlatedSubject: "Psixologiya",
    correlatedTrait: "Communication"
  },

  // 13-18: Social, Education & Human Relations
  {
    id: "q-13",
    orderNumber: 13,
    questionUz: "Sinfdoshim yoki do‘stim biror mavzuni tushunmasa, unga mehr bilan batafsil tushuntirib berish menga huzur beradi.",
    questionKrill: "Синфдошим ёки дўстим бирор мавзуни тушунмаса, унга меҳр билан батафсил тушунтириб бериш менга ҳузур беради.",
    questionRu: "Если одноклассник не понимает тему, мне в радость терпеливо и понятно всё ему объяснить.",
    questionEn: "When a classmate struggles with a topic, I genuinely enjoy explaining it step by step.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 1.0,
    weightEng: 0,
    weightSoc: 10.0,
    weightCre: 2.0,
    weightBus: 2.0,
    weightNat: 0,
    weightLaw: 1.0,
    correlatedSubject: "Adabiyot",
    correlatedTrait: "Communication"
  },
  {
    id: "q-14",
    orderNumber: 14,
    questionUz: "Katta jamoa oldida nutq so‘zlash, taqdimot qilish va odamlarni bir maqsad sari ilhomlantirish menga yoqadi.",
    questionKrill: "Катта жамоа олдида нутқ сўзлаш, тақдимот қилиш ва одамларни бир мақсад сари илҳомлантириш менга ёқади.",
    questionRu: "Мне нравится выступать перед аудиторией, проводить презентации и вдохновлять людей.",
    questionEn: "I feel comfortable speaking in public, delivering presentations, and inspiring groups of people.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 8.5,
    weightCre: 4.0,
    weightBus: 8.0,
    weightNat: 0,
    weightLaw: 5.0,
    correlatedSubject: "Ona tili",
    correlatedTrait: "Leadership"
  },
  {
    id: "q-15",
    orderNumber: 15,
    questionUz: "Kichik bolalar bilan mashg‘ulotlar o‘tkazish, ularga foydali o‘yinlar va tarbiya berish meni charchatmaydi.",
    questionKrill: "Кичик болалар билан машғулотлар ўтказиш, уларга фойдали ўйинлар ва тарбия бериш мени чарчатмайди.",
    questionRu: "Работа с маленькими детьми, обучение их через развивающие игры приносит мне искреннее удовольствие.",
    questionEn: "Teaching young kids, guiding them with creative games, and nurturing their growth does not tire me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 3.0,
    weightEng: 0,
    weightSoc: 9.5,
    weightCre: 4.0,
    weightBus: 0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Pedagogika",
    correlatedTrait: "Communication"
  },
  {
    id: "q-16",
    orderNumber: 16,
    questionUz: "Xayriya ishlari, nogironligi bor yoki yordamga muhtoj insonlarga g‘amxo‘rlik ko‘rsatishni burchim deb bilaman.",
    questionKrill: "Хайрия ишлари, ногиронлиги бор ёки ёрдамга муҳтож инсонларга ғамхўрлик кўрсатишни бурчим деб биламан.",
    questionRu: "Я считаю своим долгом участвовать в благотворительности и поддерживать людей в трудной ситуации.",
    questionEn: "I feel an inner duty to support underprivileged people and engage in community care initiatives.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 5.0,
    weightEng: 0,
    weightSoc: 9.0,
    weightCre: 0,
    weightBus: 0,
    weightNat: 1.0,
    weightLaw: 3.0,
    correlatedSubject: "Tarbiya",
    correlatedTrait: "Communication"
  },

  // 17-22: Creative, Arts & Media
  {
    id: "q-17",
    orderNumber: 17,
    questionUz: "Bo‘sh vaqtimda chiroyli rasmlar chizish, grafik dizayn qilish yoki qog‘ozda eskizlar yaratishni yaxshi ko‘raman.",
    questionKrill: "Бўш вақтимда чиройли расмлар чизиш, график дизайн қилиш ёки қоғозда эскизлар яратишни яхши кўраман.",
    questionRu: "В свободное время я с удовольствием рисую, создаю графический дизайн или делаю наброски.",
    questionEn: "In my free time, I love sketching artwork, designing graphics, or creating visual concepts.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 3.0,
    weightMed: 0,
    weightEng: 2.0,
    weightSoc: 0,
    weightCre: 10.0,
    weightBus: 2.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Tasviriy san'at",
    correlatedTrait: "Creativity"
  },
  {
    id: "q-18",
    orderNumber: 18,
    questionUz: "Video roliklar montaj qilish, professional fotosuratlar olish va ranglar bilan ishlash jarayoni menga qiziq.",
    questionKrill: "Видео роликлар монтаж қилиш, профессионал фотосуратлар олиш ва ранглар билан ишлаш жараёни менга қизиқ.",
    questionRu: "Мне нравится монтировать видеоролики, делать качественные фотографии и работать с цветокоррекцией.",
    questionEn: "I love shooting photography, editing videos, and crafting aesthetic color compositions.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 5.0,
    weightMed: 0,
    weightEng: 1.0,
    weightSoc: 2.0,
    weightCre: 9.5,
    weightBus: 3.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Informatika",
    correlatedTrait: "Creativity"
  },
  {
    id: "q-19",
    orderNumber: 19,
    questionUz: "Kiyim-kechak modasi, xonalar interyeri yoki zamonaviy bezak dizayni haqida o‘ylash menga ilhom bag‘ishlaydi.",
    questionKrill: "Кийим-кечак модаси, хоналар интерьери ёки замонавий безак дизайни ҳақида ўйлаш менга илҳом бағишлайди.",
    questionRu: "Мода, стиль одежды, дизайн интерьеров и оформление пространств по-настоящему вдохновляют меня.",
    questionEn: "Fashion trends, interior decor styling, and spatial design spark my imagination.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 1.0,
    weightMed: 0,
    weightEng: 2.0,
    weightSoc: 1.0,
    weightCre: 9.0,
    weightBus: 4.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Tasviriy san'at",
    correlatedTrait: "Creativity"
  },
  {
    id: "q-20",
    orderNumber: 20,
    questionUz: "Hikoyalar, she’rlar, maqolalar yozish yoki qiziqarli voqealarni yozma ifodalash qobiliyatim kuchli.",
    questionKrill: "Ҳикоялар, шеърлар, мақолалар ёзиш ёки қизиқарли воқеаларни ёзма ифодалаш қобилиятим кучли.",
    questionRu: "У меня есть склонность к сочинению историй, стихотворений, статей и яркому изложению событий.",
    questionEn: "I have a knack for creative storytelling, writing articles, poetry, and persuasive text.",
    category: "SUBJECT",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 4.0,
    weightCre: 9.0,
    weightBus: 3.0,
    weightNat: 0,
    weightLaw: 2.0,
    correlatedSubject: "Adabiyot",
    correlatedTrait: "Creativity"
  },

  // 21-26: Business, Finance & Leadership
  {
    id: "q-21",
    orderNumber: 21,
    questionUz: "Kichik bo‘lsa ham shaxsiy biznes yoki savdo-sotiq loyihasini boshlash, foyda va xarajatni hisoblash qiziq.",
    questionKrill: "Кичик бўлса ҳам шахсий бизнес ёки савдо-сотиқ лойиҳасини бошлаш, фойда ва харажатни ҳисоблаш қизиқ.",
    questionRu: "Мне интересна идея запустить собственный бизнес, продавать товары и просчитывать доходы и расходы.",
    questionEn: "The idea of launching my own enterprise, selling goods, and calculating profits appeals to me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 1.0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 2.0,
    weightCre: 2.0,
    weightBus: 10.0,
    weightNat: 0,
    weightLaw: 3.0,
    correlatedSubject: "Iqtisod",
    correlatedTrait: "Leadership"
  },
  {
    id: "q-22",
    orderNumber: 22,
    questionUz: "Biror mahsulotni odamlarga qanday qilib chiroyli reklama qilish va uni sotib olishga jalb qilishni rejalashtirish yoqadi.",
    questionKrill: "Бирор маҳсулотни одамларга қандай қилиб чиройли реклама қилиш ва уни сотиб олишга жалб қилишни режалаштириш ёқади.",
    questionRu: "Мне нравится продумывать рекламные ходы: как презентовать продукт так, чтобы его захотели купить.",
    questionEn: "I enjoy planning marketing strategies: how to promote a product so customers desire to buy it.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 2.0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 4.0,
    weightCre: 6.0,
    weightBus: 9.0,
    weightNat: 0,
    weightLaw: 1.0,
    correlatedSubject: "Iqtisod",
    correlatedTrait: "Leadership"
  },
  {
    id: "q-23",
    orderNumber: 23,
    questionUz: "Pul mablag‘larini tejash, to‘g‘ri taqsimlash, bank hisoblari va investitsiya mavzulariga befarq emasman.",
    questionKrill: "Пул маблағларини тежаш, тўғри тақсимлаш, банк ҳисоблари ва инвестиция мавзуларига бефарқ эмасман.",
    questionRu: "Я внимательно отношусь к деньгам, умею распределять бюджет и интересуюсь инвестициями.",
    questionEn: "I am mindful of budgeting, saving, banking operations, and investment strategies.",
    category: "SUBJECT",
    active: true,
    weightTech: 2.0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 0,
    weightCre: 0,
    weightBus: 9.5,
    weightNat: 0,
    weightLaw: 3.0,
    correlatedSubject: "Matematika",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-24",
    orderNumber: 24,
    questionUz: "Guruh bilan ishlaganda reja tuzish, vazifalarni bo‘lib berish va natijani nazorat qilishni o‘z zimmamga olaman.",
    questionKrill: "Гуруҳ билан ишлаганда режа тузиш, вазифаларни бўлиб бериш ва натижани назорат қилишни ўз зиммамга оламан.",
    questionRu: "Работая в группе, я беру на себя составление плана, распределение задач и контроль результатов.",
    questionEn: "When working in teams, I readily coordinate the schedule, assign tasks, and track outcomes.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 1.0,
    weightMed: 0,
    weightEng: 1.0,
    weightSoc: 5.0,
    weightCre: 1.0,
    weightBus: 8.5,
    weightNat: 0,
    weightLaw: 4.0,
    correlatedSubject: "Ona tili",
    correlatedTrait: "Leadership"
  },

  // 25-30: Nature, Agriculture & Environment
  {
    id: "q-25",
    orderNumber: 25,
    questionUz: "O‘simliklar yetishtirish, bog‘dorchilik, mevali daraxtlar va gullarni parvarish qilish menga huzur bag‘ishlaydi.",
    questionKrill: "Ўсимликлар етиштириш, боғдорчилик, мевали дарахтлар ва гулларни парвариш қилиш менга ҳузур бағишлайди.",
    questionRu: "Выращивание растений, садоводство, уход за деревьями и цветами приносят мне душевный покой.",
    questionEn: "Growing plants, horticulture, and nurturing fruit gardens bring me genuine fulfillment.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 1.0,
    weightEng: 1.0,
    weightSoc: 0,
    weightCre: 2.0,
    weightBus: 3.0,
    weightNat: 10.0,
    weightLaw: 0,
    correlatedSubject: "Biologiya",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-26",
    orderNumber: 26,
    questionUz: "Uy va fermer hayvonlarini boqish, ularning kasalliklarini davolash va zotlarini yaxshilash qiziq.",
    questionKrill: "Уй ва фермер ҳайвонларини боқиш, уларнинг касалликларини даволаш ва зотларини яхшилаш қизиқ.",
    questionRu: "Мне нравится ухаживать за домашними и фермерскими животными, лечить их и заботиться о них.",
    questionEn: "Caring for animals, diagnosing their ailments, and improving livestock conditions interest me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 6.0,
    weightEng: 0,
    weightSoc: 0,
    weightCre: 0,
    weightBus: 3.0,
    weightNat: 9.5,
    weightLaw: 0,
    correlatedSubject: "Biologiya",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-27",
    orderNumber: 27,
    questionUz: "Suv resurslarini tejash, tomchilatib sug‘orish va zamonaviy issiqxona (agro-texnologiya) tizimlari menga ma’qul.",
    questionKrill: "Сув ресурсларини тежаш, томчилатиб суғориш ва замонавий иссиқхона (агро-технология) тизимлари менга маъқул.",
    questionRu: "Мне интересны технологии капельного орошения, сбережения воды и современные теплицы.",
    questionEn: "I am intrigued by water-saving drip irrigation, automated greenhouses, and agritech systems.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 4.0,
    weightMed: 0,
    weightEng: 6.0,
    weightSoc: 0,
    weightCre: 0,
    weightBus: 4.0,
    weightNat: 8.5,
    weightLaw: 0,
    correlatedSubject: "Geografiya",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-28",
    orderNumber: 28,
    questionUz: "Ekologiyani asrash, havoning ifloslanishiga qarshi kurashish va qayta tiklanuvchi energiya (quyosh, shamol) yoqadi.",
    questionKrill: "Экологияни асраш, ҳавонинг ифлосланишига қарши курашиш ва қайта тикланувчи энергия (қуёш, шамол) ёқади.",
    questionRu: "Мне близка тема защиты окружающей среды, очистки воздуха и возобновляемой энергетики (солнце, ветер).",
    questionEn: "I care about climate preservation, fighting pollution, and developing solar and clean energy.",
    category: "SUBJECT",
    active: true,
    weightTech: 3.0,
    weightMed: 2.0,
    weightEng: 5.0,
    weightSoc: 2.0,
    weightCre: 0,
    weightBus: 2.0,
    weightNat: 9.0,
    weightLaw: 2.0,
    correlatedSubject: "Geografiya",
    correlatedTrait: "Problem solving"
  },

  // 29-34: Law, Security & Order
  {
    id: "q-29",
    orderNumber: 29,
    questionUz: "Jamiyatda qonun ustuvorligi, qat’iy intizom va insonlarning huquqlarini himoya qilish muhim deb hisoblayman.",
    questionKrill: "Жамиятда қонун устуворлиги, қатъий интизом ва инсонларнинг ҳуқуқларини ҳимоя қилиш муҳим деб ҳисоблайман.",
    questionRu: "Я убежден в важности верховенства закона, железной дисциплины и защиты прав граждан.",
    questionEn: "I believe upholding the rule of law, strict discipline, and human rights is essential for society.",
    category: "SUBJECT",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 4.0,
    weightCre: 0,
    weightBus: 2.0,
    weightNat: 0,
    weightLaw: 10.0,
    correlatedSubject: "Huquq",
    correlatedTrait: "Leadership"
  },
  {
    id: "q-30",
    orderNumber: 30,
    questionUz: "Murakkab janjallar yoki bahsli vaziyatlarda har ikki tomonni xolis eshitib, adolatli qaror chiqarishga intilaman.",
    questionKrill: "Мураккаб жанжаллар ёки баҳсли вазиятларда ҳар икки томонни холис эшитиб, адолатли қарор чиқаришга интиламан.",
    questionRu: "В конфликтных спорах я стремлюсь беспристрастно выслушать обе стороны и найти справедливое решение.",
    questionEn: "In disputes, I impartially listen to both viewpoints and strive to deliver an equitable judgment.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 5.0,
    weightCre: 0,
    weightBus: 3.0,
    weightNat: 0,
    weightLaw: 9.0,
    correlatedSubject: "Huquq",
    correlatedTrait: "Problem solving"
  },
  {
    id: "q-31",
    orderNumber: 31,
    questionUz: "Harbiy soha, jismoniy chaqqonlik, chegaralarni qo‘riqlash yoki favqulodda vaziyatlarda xavfsizlikni ta’minlash qiziq.",
    questionKrill: "Ҳарбий соҳа, жисмоний чаққонлик, чегараларни қўриқлаш ёки фавқулодда вазиятларда хавфсизликни таъминлаш қизиқ.",
    questionRu: "Меня привлекает военная служба, физическая закалка, охрана порядка и действия в чрезвычайных ситуациях.",
    questionEn: "Military service, physical agility, emergency response, and defense security appeal to me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 1.0,
    weightMed: 2.0,
    weightEng: 2.0,
    weightSoc: 2.0,
    weightCre: 0,
    weightBus: 0,
    weightNat: 1.0,
    weightLaw: 9.5,
    correlatedSubject: "Jismoniy tarbiya",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-32",
    orderNumber: 32,
    questionUz: "Tergov jarayonlari, dalillarni mantiqan tahlil qilish va yashirin sirlarni fosh etish mavzulari meni o‘ylantiradi.",
    questionKrill: "Тергов жараёнлари, далилларни мантиқан таҳлил қилиш ва яширин сирларни фош этиш мавзулари мени ўйлантиради.",
    questionRu: "Мне интересна криминалистика, сопоставление улик и раскрытие запутанных тайн логическим путем.",
    questionEn: "Criminology, evaluating investigative evidence, and unraveling mysterious cases excite me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 3.0,
    weightMed: 2.0,
    weightEng: 0,
    weightSoc: 2.0,
    weightCre: 1.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 9.0,
    correlatedSubject: "Tarix",
    correlatedTrait: "Problem solving"
  },

  // 33-36: Transport, Mechanics & Modern Industry
  {
    id: "q-33",
    orderNumber: 33,
    questionUz: "Avtomobillar dvigateli, elektromobillar tuzilishi va ularning elektron diagnostikasi bilan qiziqaman.",
    questionKrill: "Автомобиллар двигатели, электромобиллар тузилиши ва уларнинг электрон диагностикаси билан қизиқаман.",
    questionRu: "Мне интересно устройство автомобильных двигателей, электрокаров и их компьютерная диагностика.",
    questionEn: "I am curious about automotive engines, electric vehicle tech, and digital car diagnostics.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 5.0,
    weightMed: 0,
    weightEng: 9.0,
    weightSoc: 0,
    weightCre: 0,
    weightBus: 3.0,
    weightNat: 0,
    weightLaw: 0,
    correlatedSubject: "Fizika",
    correlatedTrait: "Practical work"
  },
  {
    id: "q-34",
    orderNumber: 34,
    questionUz: "Samolyotlar, dronlarni boshqarish yoki ularning aerodinamikasi haqida ko‘proq ma’lumot olishni istayman.",
    questionKrill: "Самолетлар, дронларни бошқариш ёки уларнинг аэродинамикаси ҳақида кўпроқ маълумот олишни истайман.",
    questionRu: "Я хочу научиться управлять дронами, самолетами и больше узнать об авиационной аэродинамике.",
    questionEn: "I want to pilot drones, explore aviation mechanics, and study aerodynamic engineering.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 7.0,
    weightMed: 0,
    weightEng: 8.5,
    weightSoc: 0,
    weightCre: 2.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 2.0,
    correlatedSubject: "Fizika",
    correlatedTrait: "Technical thinking"
  },
  {
    id: "q-35",
    orderNumber: 35,
    questionUz: "Chet tillarini (masalan, ingliz, rus, nemis) chuqur o‘rganib, chet elliklar bilan erkin muloqot qilishni xohlayman.",
    questionKrill: "Чет тилларини (масалан, инглиз, рус, немис) чуқур ўрганиб, чет элликлар билан эркин мулоқот қилишни хоҳлайман.",
    questionRu: "Я хочу свободно владеть иностранными языками (английским, немецким и др.) и общаться с миром.",
    questionEn: "I want to master foreign languages and communicate effortlessly across international cultures.",
    category: "SUBJECT",
    active: true,
    weightTech: 3.0,
    weightMed: 1.0,
    weightEng: 1.0,
    weightSoc: 8.0,
    weightCre: 4.0,
    weightBus: 7.0,
    weightNat: 0,
    weightLaw: 3.0,
    correlatedSubject: "Ingliz tili",
    correlatedTrait: "Communication"
  },
  {
    id: "q-36",
    orderNumber: 36,
    questionUz: "Oshpazlik, yangi taomlar retseptini kashf qilish yoki mehmondo‘stlik xizmatlarini tashkil etish yoqadi.",
    questionKrill: "Ошпазлик, янги таомлар рецептини кашф қилиш ёки меҳмондўстлик хизматларини ташкил этиш ёқади.",
    questionRu: "Мне нравится кулинария, создание оригинальных рецептов и организация гостеприимного сервиса.",
    questionEn: "Culinary arts, inventing innovative recipes, and organizing hospitable dining delight me.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 1.0,
    weightEng: 1.0,
    weightSoc: 4.0,
    weightCre: 6.0,
    weightBus: 6.0,
    weightNat: 2.0,
    weightLaw: 0,
    correlatedSubject: "Mehnat",
    correlatedTrait: "Practical work"
  },

  // 37-40: Work Style, Freedom of Choice & Family Influence (Indirect checks)
  {
    id: "q-37",
    orderNumber: 37,
    questionUz: "Biror vazifani bajarishda kimgadir bog‘liq bo‘lmasdan, mustaqil ravishda rejalashtirib ishlashni afzal ko‘raman.",
    questionKrill: "Бирор вазифани бажаришда кимгадир боғлиқ бўлмасдан, мустақил равишда режалаштириб ишлашни афзал кўраман.",
    questionRu: "При выполнении задач я предпочитаю действовать самостоятельно, без лишнего внешнего контроля.",
    questionEn: "When executing tasks, I prefer working independently with autonomy rather than micromanagement.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 4.0,
    weightMed: 2.0,
    weightEng: 4.0,
    weightSoc: 0,
    weightCre: 5.0,
    weightBus: 5.0,
    weightNat: 3.0,
    weightLaw: 0,
    correlatedTrait: "Independent work"
  },
  {
    id: "q-38",
    orderNumber: 38,
    questionUz: "Kun bo‘yi bir joyda ofisda o‘tirishdan ko‘ra, harakatda bo‘lish yoki sayohat qilish imkoniyati bor kasblar ma’qul.",
    questionKrill: "Кун бўйи бир жойда офисда ўтиришдан кўра, ҳаракатда бўлиш ёки саёҳат қилиш имконияти бор касблар маъқул.",
    questionRu: "Вместо сидения в офисе мне ближе динамичные профессии с разъездами или физической активностью.",
    questionEn: "I prefer dynamic professions involving travel and physical movement over desk-bound office routines.",
    category: "BEHAVIOR",
    active: true,
    weightTech: 0,
    weightMed: 3.0,
    weightEng: 5.0,
    weightSoc: 3.0,
    weightCre: 3.0,
    weightBus: 4.0,
    weightNat: 6.0,
    weightLaw: 4.0,
    correlatedTrait: "Practical work"
  },
  {
    id: "q-39",
    orderNumber: 39,
    questionUz: "Kelajakdagi kasbingizni tanlashda o‘z qiziqishlaringiz va qaroringizni oilangiz bilan erkin muhokama qila olasizmi?",
    questionKrill: "Келажакдаги касбингизни танлашда ўз қизиқишларингиз ва қарорингизни оилангиз билан эркин муҳокама қила оласизми?",
    questionRu: "Можете ли вы открыто обсуждать выбор своей будущей профессии с семьей без давления?",
    questionEn: "Can you freely discuss your genuine career aspirations with your family without undue pressure?",
    category: "PRESSURE",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 2.0,
    weightCre: 0,
    weightBus: 0,
    weightNat: 0,
    weightLaw: 0,
    isPressureCheck: true,
    correlatedTrait: "Independent work"
  },
  {
    id: "q-40",
    orderNumber: 40,
    questionUz: "Agar hech kim sizga kasb tanlash bo‘yicha majburiy maslahat bermasa, faqat o‘zingiz chin dildan sevgan ishni tanlarmidingiz?",
    questionKrill: "Агар ҳеч ким сизга касб танлаш бўйича мажбурий маслаҳат бермаса, фақат ўзингиз чин дилдан севган ишни танлармидингиз?",
    questionRu: "Если бы никто не советовал вам профессию против воли, выбрали бы вы исключительно то, к чему лежит душа?",
    questionEn: "If unconstrained by outside opinions, would you pursue strictly the calling you genuinely love?",
    category: "PRESSURE",
    active: true,
    weightTech: 0,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 1.0,
    weightCre: 1.0,
    weightBus: 1.0,
    weightNat: 0,
    weightLaw: 0,
    isPressureCheck: true,
    correlatedTrait: "Independent work"
  }
];

export const CAREER_CATEGORIES = [
  "Technology",
  "Medicine",
  "Engineering",
  "Construction",
  "Automotive",
  "Agriculture",
  "Education",
  "Business",
  "Finance",
  "Creative",
  "Media",
  "Science",
  "Environment",
  "Law",
  "Security",
  "Transport",
  "Logistics",
  "Energy",
  "Telecommunications",
  "Manufacturing",
  "Beauty",
  "Food",
  "Tourism",
  "Hospitality",
  "Government"
];
