import { Career } from '../../src/types';

export const AUTO_AGRO_CAREERS: Career[] = [
  {
    id: "car-auto-1",
    slug: "auto-mechanic",
    nameUz: "Avtomexanik (Auto Mechanic)",
    nameKrill: "Автомеханик (Auto Mechanic)",
    nameRu: "Автомеханик",
    nameEn: "Automotive Mechanic",
    category: "Automotive",
    imageUrl: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Avtomobillarning dvigateli, uzatmalar qutisi, tormoz va yurish qismlarini ta'mirlab, soz holatga keltiruvchi usta.",
    descriptionKrill: "Автомобилларнинг двигатели, узатмалар қутиси, тормоз ва юриш қисмларини таъмирлаб, соз ҳолатга келтирувчи уста.",
    descriptionRu: "Диагностирует и ремонтирует двигатели внутреннего сгорания, ходовую часть и тормозные системы автомобилей.",
    descriptionEn: "Inspects, services, and repairs internal combustion engines, transmissions, brake systems, and suspensions.",
    skills: ["Dvigatel tuzilishi", "Gidravlika & pnevmatika", "Chilangarlik asboblari", "Nosozlikni eshitib aniqlash"],
    subjects: ["Fizika (Mexanika)", "Mehnat ta'limi", "Geometriya"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Avto tuzilishi", items: ["Dvigatel 4 taktli sikli", "Moylash va sovutish tizimi", "Xavfsizlik va asboblar"] },
      stage2: { period: "3–6 oy", title: "Yurish qismi", items: ["Podveska va amortizatorlar", "Tormoz kolodkalari va disklari", "Rul mexanizmi"] },
      stage3: { period: "6–12 oy", title: "Transmissiya & Motor", items: ["Mexanik va avtomat karobka", "Dvigatel kap-remonti", "Klapanlarni sozlash"] },
      stage4: { period: "1–2 yil", title: "Zamonaviy servis", items: ["Xorijiy avtomobillar servisi", "Shaxsiy avtoservis boshqaruvi"] }
    },
    educationPath: "Avtomobilsozlik kollejlari, Andijon Mashinasozlik Instituti, Turin Politexnika",
    futureOutlook: "Avtomobillar soni har yili oshib borayotganligi sababli usta mexaniklarga navbat doim ko‘p.",
    relatedCareers: ["Auto Electrician", "EV Technician", "Automotive Engineer"],
    weightTech: 20,
    weightMed: 0,
    weightEng: 90,
    weightSoc: 10,
    weightCre: 15,
    weightBus: 40,
    weightNat: 0,
    weightLaw: 5,
    active: true
  },
  {
    id: "car-auto-2",
    slug: "auto-electrician",
    nameUz: "Avtoelektrik / Diagnostika Mutaxassisi",
    nameKrill: "Автоэлектрик / Диагностика Мутахассиси",
    nameRu: "Автоэлектрик-диагност",
    nameEn: "Automotive Electrician & Diagnostician",
    category: "Automotive",
    imageUrl: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Avtomobillarning kompyuter bloki (ECU), datchiklari, simlari va audio-xavfsizlik tizimlarini skanerlar orqali tekshirib tuzatuvchi mutaxassis.",
    descriptionKrill: "Автомобилларнинг компьютер блоки (ECU), датчиклари, симлари ва аудио-хавфсизлик тизимларини сканерлар орқали текшириб тузатувчи мутахассис.",
    descriptionRu: "Проводит компьютерную диагностику электронных блоков управления (ЭБУ), датчиков и проводки современных авто.",
    descriptionEn: "Diagnoses vehicle electronics, ECU mapping, sensors, wiring harnesses, and digital instrument clusters.",
    skills: ["OBD-II skanerlar", "Multimetr va ossillograf", "Avto sxemalari o'qish", "Firmware / Proshivka"],
    subjects: ["Fizika (Elektr bo'limi)", "Informatika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Avtoelektr asoslari", items: ["12V/24V tarmoq", "Rele va saqlagichlar", "Simlarni ta'mirlash"] },
      stage2: { period: "3–6 oy", title: "Datchiklar & ECU", items: ["Kislorod, ABS, havo datchiklari", "Skaner bilan xatolarni o'qish", "Generator va starter"] },
      stage3: { period: "6–12 oy", title: "CAN-shina & Chip-tuning", items: ["CAN protokoli signallari", "Immobolayzer va pultlar", "Elektron bloklarni dasturlash"] },
      stage4: { period: "1–2 yil", title: "Elektromobillar", items: ["Gibrid va Tesla/BYD tizimlari", "Yuqori kuchlanishli batareyalar"] }
    },
    educationPath: "Turin Politexnika Universiteti, Andijon Mashinasozlik Instituti, maxsus sertifikatlar",
    futureOutlook: "Zamonaviy avtomobillarning 80% qismi elektronikadan iborat. Eng yuqori daromadli avto kasblardan biri.",
    relatedCareers: ["Auto Mechanic", "Electrical Engineer", "Embedded Developer"],
    weightTech: 75,
    weightMed: 0,
    weightEng: 90,
    weightSoc: 15,
    weightCre: 10,
    weightBus: 45,
    weightNat: 0,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-auto-3",
    slug: "drone-pilot",
    nameUz: "Dron Operator / Aerofotosurat Mutaxassisi",
    nameKrill: "Дрон Оператор / Аэрофотосурат Мутахассиси",
    nameRu: "Оператор беспилотных летательных аппаратов (БПЛА)",
    nameEn: "UAV / Commercial Drone Pilot",
    category: "Transport",
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Uchuvchisiz uchish apparatlarini (dronlar) professional boshqarib, qishloq xo‘jaligi, xaritalash, kino va qidiruv ishlarida xizmat ko‘rsatuvchi mutaxassis.",
    descriptionKrill: "Учувчисиз учиш аппаратларини (дронлар) профессионал бошқариб, қишлоқ хўжалиги, хариталаш, кино ва қидирув ишларида хизмат кўрсатувчи мутахассис.",
    descriptionRu: "Пилотирует БПЛА для агрохимической обработки полей, картографии, киносъемок и мониторинга объектов.",
    descriptionEn: "Pilots commercial UAVs, aerial mapping flights, agricultural crop monitoring, and cinematic videography.",
    skills: ["Dron boshqaruv pulti", "Aerofotosurat & GPS", "Agrodronlar kalibratsiyasi", "Aviatsiya qoidalari"],
    subjects: ["Fizika", "Geografiya", "Informatika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Simulator & Qoidalar", items: ["Parvoz xavfsizligi qoidalari", "FPV simulatorida mashq", "Batareyalar xavfsizligi"] },
      stage2: { period: "3–6 oy", title: "Haqiqiy parvoz", items: ["DJI dronlar boshqaruvi", "Kamera stabilizatsiyasi", "Ob-havo sharoitlarini baholash"] },
      stage3: { period: "6–12 oy", title: "Sanoat va Agro dronlar", items: ["Dala ustida dori sepish", "3D xaritalash (Pix4D)", "Termovizor kameralar"] },
      stage4: { period: "1–2 yil", title: "Litsenziyali operator", items: ["Fuqaro aviatsiyasi litsenziyasi", "Dronlarga texnik xizmat ko'rsatish"] }
    },
    educationPath: "Toshkent Davlat Aviatsiya Instituti, Raqamli geodeziya markazlari",
    futureOutlook: "Agrosanoat, qutqaruv, monitoring va logistikada dronlar inqilob yaratmoqda.",
    relatedCareers: ["Robotics Engineer", "Surveyor", "Agronomist"],
    weightTech: 80,
    weightMed: 0,
    weightEng: 80,
    weightSoc: 10,
    weightCre: 65,
    weightBus: 35,
    weightNat: 45,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-agro-1",
    slug: "agronomist",
    nameUz: "Agronom / O‘simlikshunos Olim",
    nameKrill: "Агроном / Ўсимликшунос Олим",
    nameRu: "Ученый-агроном",
    nameEn: "Agronomist / Plant Scientist",
    category: "Agriculture",
    imageUrl: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Ekin maydonlarining unumdorligini oshiruvchi, urug‘chilik, o‘g‘itlash va hosildorlikni ilmiy asosda boshqaruvchi dala me'mori.",
    descriptionKrill: "Экин майдонларининг унумдорлигини оширувчи, уруғчилик, ўғитлаш ва ҳосилдорликни илмий асосда бошқарувчи дала меъмори.",
    descriptionRu: "Управляет плодородием почвы, рассчитывает графики посева и удобрений, обеспечивая высокий урожай.",
    descriptionEn: "Maximizes crop yield, manages soil fertility, seeds selection, and sustainable crop rotation strategies.",
    skills: ["Tuproq tahlili", "O'g'itlash me'yorlari", "Kasallik va zararkunandalar", "Hosilni rejalashtirish"],
    subjects: ["Biologiya", "Kimyo", "Geografiya"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Tuproq & Urug'", items: ["Tuproq tarkibi va pH darajasi", "Urug'larning unib chiqishi", "Mavsumiy kalendar"] },
      stage2: { period: "3–6 oy", title: "O'g'itlar & Oziqlantirish", items: ["Azot, fosfor, kaliy me'yorlari", "Organik o'g'itlar", "Bargdan oziqlantirish"] },
      stage3: { period: "6–12 oy", title: "O'simlik himoyasi", items: ["Fungitsid va insektitsidlar", "Biologik himoya usullari", "Zararkunandalarni aniqlash"] },
      stage4: { period: "1–2 yil", title: "Agro universitet", items: ["Toshkent Davlat Agrar Universiteti (TDAU)", "Intensiv bog'dorchilik amaliyoti"] }
    },
    educationPath: "Toshkent Davlat Agrar Universiteti (TDAU), Samarqand Agrar Instituti",
    futureOutlook: "Oziq-ovqat xavfsizligi butun dunyoda 1-o‘rinda turadi. Malakali agronomlarga talab nihoyatda katta.",
    relatedCareers: ["Greenhouse Specialist", "Animal Scientist", "Ecologist"],
    weightTech: 20,
    weightMed: 15,
    weightEng: 25,
    weightSoc: 15,
    weightCre: 10,
    weightBus: 50,
    weightNat: 100,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-agro-2",
    slug: "veterinarian",
    nameUz: "Veterinar Shifokor",
    nameKrill: "Ветеринар Шифокор",
    nameRu: "Ветеринарный врач",
    nameEn: "Veterinarian",
    category: "Agriculture",
    imageUrl: "https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Uy va chorva hayvonlarining salomatligini asrovchi, ularni emlovchi, operatsiya qiluvchi va kasalliklardan davolovchi mehribon shifokor.",
    descriptionKrill: "Уй ва чорва ҳайвонларининг саломатлигини асровчи, уларни эмловчи, операция қилувчи ва касалликлардан даволовчи меҳрибон шифокор.",
    descriptionRu: "Лечит домашних питомцев и сельскохозяйственный скот, проводит хирургические операции и вакцинацию.",
    descriptionEn: "Diagnoses and treats domestic pets and farm livestock, performs surgeries, and ensures zoonotic disease control.",
    skills: ["Hayvonlar anatomiyasi", "Veterinariya dorilari", "Emlash", "Jarrohlik amaliyoti"],
    subjects: ["Biologiya", "Kimyo", "Lotin tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Hayvon anatomiyasi", items: ["Qoramol, qo'y va uy hayvonlari tuzilishi", "Fiziologiya asoslari", "Hayvonlarni ushlash qoidalari"] },
      stage2: { period: "3–6 oy", title: "Veterinar farmakologiya", items: ["Veterinar dori vositalari", "Vaksinalar va zardoblar", "Yuqumli kasalliklar profilaktikasi"] },
      stage3: { period: "6–12 oy", title: "Klinik diagnostika", items: ["Harorat, puls va nafas tekshirish", "Yaralarni davolash va gips", "Tug'ruqqa yordam berish"] },
      stage4: { period: "1–2 yil", title: "Veterinariya OTM", items: ["Samarqand Davlat Veterinariya Meditsinasi Universiteti", "Xususiy vet-klinika"] }
    },
    educationPath: "Samarqand Davlat Veterinariya Meditsinasi Universiteti, Toshkent filiali",
    futureOutlook: "Chorvachilik fermalari, parrandachilik va xususiy veterinariya klinikalarida doimiy yuqori ehtiyoj.",
    relatedCareers: ["General Doctor", "Animal Scientist", "Agronomist"],
    weightTech: 10,
    weightMed: 85,
    weightEng: 0,
    weightSoc: 50,
    weightCre: 10,
    weightBus: 40,
    weightNat: 95,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-agro-3",
    slug: "greenhouse-specialist",
    nameUz: "Zamonaviy Issiqxona Mutaxassisi (Agro-Tech)",
    nameKrill: "Замонавий Иссиқхона Мутахассиси (Agro-Tech)",
    nameRu: "Агроном тепличных комплексов (Agro-Tech)",
    nameEn: "Automated Greenhouse Specialist",
    category: "Agriculture",
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Gidroponika, iqlim nazorati va tomchilatib sug‘orish asosida qishin-yozin to‘xtovsiz pomidor, bodring va mevalar yetishtiruvchi innovatsion usta.",
    descriptionKrill: "Гидропоника, иқлим назорати ва томчилатиб суғориш асосида қишин-ёзин тўхтовсиз помидор, бодринг ва мевалар етиштирувчи инновацион уста.",
    descriptionRu: "Управляет микроклиматом современных тепличных комплексов, гидропоникой и автоматизированным питанием растений.",
    descriptionEn: "Oversees climate-controlled greenhouse complexes, automated hydroponic nutrient feeding, and year-round harvesting.",
    skills: ["Gidroponika tizimlari", "Iqlim nazorati sensorlari", "O'simliklar oziqlanishi (EC/pH)", "Issiqlik tejash"],
    subjects: ["Biologiya", "Fizika", "Kimyo", "Informatika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Issiqxona asoslari", items: ["Issiqxona turlari", "Gidroponika (substrat, kokos)", "EC va pH o'lchash"] },
      stage2: { period: "3–6 oy", title: "Avtomatika", items: ["Harorat va namlik kontrollerlari", "CO2 darajasi boshqaruvi", "Tomchilatib oziqlantirish"] },
      stage3: { period: "6–12 oy", title: "Hosil yetishtirish", items: ["Gul changlatish (ari turlari)", "Kasalliklarning oldini olish", "Eksport standartlari"] },
      stage4: { period: "1–2 yil", title: "Agrobiznes", items: ["Aqlli issiqxona loyihalash", "Eksport shartnomalari"] }
    },
    educationPath: "TDAU, Janubiy Koreya va Niderlandiya agro-trening dasturlari",
    futureOutlook: "O‘zbekiston meva-sabzavotlarini Rossiya va arab davlatlariga eksport qilishda eng muhim soha.",
    relatedCareers: ["Agronomist", "Solar Energy Specialist", "Robotics Engineer"],
    weightTech: 55,
    weightMed: 0,
    weightEng: 65,
    weightSoc: 10,
    weightCre: 20,
    weightBus: 60,
    weightNat: 95,
    weightLaw: 5,
    active: true
  }
];
