import { Career } from '../../src/types';

export const CONSTRUCTION_ENG_CAREERS: Career[] = [
  {
    id: "car-eng-1",
    slug: "architect",
    nameUz: "Me'mor / Arxitektor",
    nameKrill: "Меъмор / Архитектор",
    nameRu: "Архитектор",
    nameEn: "Architect",
    category: "Construction",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Shaharsozlik, osmono‘par binolar, maktablar va turar-joylarning tashqi ko‘rinishi va qulay rejasini chizuvchi ijodkor muhandis.",
    descriptionKrill: "Шаҳарсозлик, осмонўпар бинолар, мактаблар ва турар-жойларнинг ташқи кўриниши ва қулай режасини чизувчи ижодкор муҳандис.",
    descriptionRu: "Проектирует концептуальный облик и внутреннюю планировку жилых, общественных и коммерческих зданий.",
    descriptionEn: "Conceives architectural forms, spatial layouts, blueprints, and urban environments blending art with physics.",
    skills: ["AutoCAD / Revit", "3D Modellashtirish (3ds Max / Blender)", "Chizmachilik", "Shaharsozlik qoidalari", "Ijodiy fantaziya"],
    subjects: ["Chizmachilik", "Geometriya", "Fizika", "Tasviriy san'at"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Chizma & Eskiz", items: ["Qo'lda eskiz chizish", "Aksonometriya va istiqbol", "Chizmachilik standartlari"] },
      stage2: { period: "3–6 oy", title: "2D & 3D Dasturlar", items: ["AutoCAD asoslari", "Revit BIM modellash", "Binolar rejasini chizish"] },
      stage3: { period: "6–12 oy", title: "Material & Konstruksiya", items: ["Qurilish materiallari xususiyatlari", "Yorug'lik va akustika", "Portfolioda 3 ta loyiha"] },
      stage4: { period: "1–2 yil", title: "Arxitektura diplomi", items: ["Toshkent Arxitektura-Qurilish Universiteti (TAQU)", "Litsenziyali me'morlik"] }
    },
    educationPath: "Toshkent Arxitektura-Qurilish Universiteti (TAQU), Samarqand Davlat Arxitektura-Qurilish Universiteti",
    futureOutlook: "O‘zbekistonda Yangi Toshkent va barcha viloyatlarda qurilish ko‘lami yuqori bo‘lib, talab doimiy yuqori.",
    relatedCareers: ["Civil Engineer", "Interior Designer", "Surveyor"],
    weightTech: 40,
    weightMed: 0,
    weightEng: 85,
    weightSoc: 25,
    weightCre: 95,
    weightBus: 35,
    weightNat: 15,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-eng-2",
    slug: "civil-engineer",
    nameUz: "Qurilish Muhandisi (Civil Engineer)",
    nameKrill: "Қурилиш Муҳандиси (Civil Engineer)",
    nameRu: "Инженер-строитель",
    nameEn: "Civil Engineer",
    category: "Engineering",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Binolar, ko‘priklar, yo‘llar va tunnellarning mustahkamligi, seysmik bardoshliligi va xavfsizligini hisoblab qurilishga rahbarlik qiluvchi muhandis.",
    descriptionKrill: "Бинолар, кўприклар, йўллар ва туннелларнинг мустаҳкамлиги, сейсмик бардошлилиги ва хавфсизлигини ҳисоблаб қурилишга раҳбарлик қилувчи муҳандис.",
    descriptionRu: "Рассчитывает нагрузки, прочность несущих железобетонных конструкций и контролирует процесс стройки.",
    descriptionEn: "Calculates structural loads, seismic endurance, concrete reinforcement, and oversees civil infrastructure erection.",
    skills: ["Konstruksiyalar hisobi", "LIRA-SAPR / SAP2000", "Qurilish nazorati", "Seysmik xavfsizlik"],
    subjects: ["Fizika (Mexanika)", "Matematika", "Chizmachilik"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Nazariy mexanika", items: ["Kuchlar taqsimoti", "Materiallar qarshiligi (Sopromat)", "Geodeziya asoslari"] },
      stage2: { period: "3–6 oy", title: "Temir-beton & Metall", items: ["Armatura hisoblash", "Beton markalari", "SNiP va ShNQ standartlari"] },
      stage3: { period: "6–12 oy", title: "Hisoblash dasturlari", items: ["LIRA / SCAD dasturlari", "Zilzilabardoshlik hisoblari", "Smeta tuzish"] },
      stage4: { period: "1–2 yil", title: "Qurilish maydonchasi", items: ["Prorab va Bosh muhandis amaliyoti", "Katta inshootlar qurilishi"] }
    },
    educationPath: "TAQU, TDTU, SamDAQI",
    futureOutlook: "Infratuzilma, magistral yo‘llar va yirik sanoat obyektlari qurilishida asosiy boshqaruvchi.",
    relatedCareers: ["Architect", "Construction Manager", "Structural Engineer"],
    weightTech: 35,
    weightMed: 0,
    weightEng: 100,
    weightSoc: 25,
    weightCre: 30,
    weightBus: 45,
    weightNat: 10,
    weightLaw: 30,
    active: true
  },
  {
    id: "car-eng-3",
    slug: "electrical-engineer",
    nameUz: "Elektr Muhandisi (Electrical Engineer)",
    nameKrill: "Электр Муҳандиси (Electrical Engineer)",
    nameRu: "Инженер-электрик",
    nameEn: "Electrical Engineer",
    category: "Energy",
    imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Elektr stansiyalari, podstansiyalar, yuqori kuchlanishli liniyalar va sanoat elektr tarmoqlarini loyihalovchi va sozlovchi muhandis.",
    descriptionKrill: "Электр станциялари, подстанциялар, юқори кучланишли линиялар ва саноат электр тармоқларини лойиҳаловчи ва созловчи муҳандис.",
    descriptionRu: "Проектирует энергосети, распределительные подстанции, трансформаторы и высоковольтные системы.",
    descriptionEn: "Designs electrical transmission grids, substations, transformer banks, and high-voltage power networks.",
    skills: ["Elektr zanjirlari hisobi", "Transformatorlar va rele himoyasi", "Xavfsizlik texnikasi", "Chizmalar o'qish"],
    subjects: ["Fizika (Elektr bo'limi)", "Matematika", "Informatika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Elektr nazariyasi", items: ["Ohm va Kirchhoff qonunlari", "O'zgaruvchan tok", "Elektr xavfsizligi guruhi"] },
      stage2: { period: "3–6 oy", title: "Sxematexnika", items: ["Elektr chizmalarini chizish", "Avtomatlar va UZO tanlash", "Kabellar kesimini hisoblash"] },
      stage3: { period: "6–12 oy", title: "Sanoat tarmoqlari", items: ["Podstansiyalar rele himoyasi", "SCADA tizimlari", "Faza muvozanati"] },
      stage4: { period: "1–2 yil", title: "Energetika diplom", items: ["Toshkent Davlat Texnika Universiteti Energetika fakulteti"] }
    },
    educationPath: "TDTU Energetika fakulteti, Farg‘ona Politexnika Instituti",
    futureOutlook: "Energiya yetishmovchiligi davrida har bir zamonaviy sanoatning qon tomiri hisoblanadi.",
    relatedCareers: ["Solar Energy Specialist", "Auto Electrician", "Robotics Engineer"],
    weightTech: 50,
    weightMed: 0,
    weightEng: 95,
    weightSoc: 10,
    weightCre: 15,
    weightBus: 25,
    weightNat: 15,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-eng-4",
    slug: "solar-energy-specialist",
    nameUz: "Quyosh Energiyasi Mutaxassisi (Solar Tech)",
    nameKrill: "Қуёш Энергияси Мутахассиси (Solar Tech)",
    nameRu: "Специалист по солнечной энергетике",
    nameEn: "Solar Energy Specialist",
    category: "Energy",
    imageUrl: "https://images.unsplash.com/photo-1509391365360-2e959784a276?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Yashil energetika — quyosh panellari, invertorlar va akkumulyator tizimlarini o‘rnatuvchi va ekspluatatsiya qiluvchi zamonaviy mutaxassis.",
    descriptionKrill: "Яшил энергетика — қуёш панеллари, инверторлар ва аккумулятор тизимларини ўрнатувчи ва эксплуатация қилувчи замонавий мутахассис.",
    descriptionRu: "Рассчитывает и монтирует фотоэлектрические солнечные электростанции, инверторы и накопители энергии.",
    descriptionEn: "Installs photovoltaic solar arrays, high-capacity inverter banks, and renewable green energy stations.",
    skills: ["Quyosh panellari montaji", "Invertorlar sozlash", "PVsyst dasturi", "Energiya hisobi"],
    subjects: ["Fizika", "Geografiya", "Matematika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Fotoelementlar asoslari", items: ["Quyosh nurlanish xaritasi", "Monokristall panellar", "Doimiy va o'zgaruvchan tok"] },
      stage2: { period: "3–6 oy", title: "Tizim loyihalash", items: ["On-grid va Off-grid tizimlar", "Akkumulyatorlar (LiFePO4)", "PVsyst dasturi"] },
      stage3: { period: "6–12 oy", title: "Montaj & Ulanish", items: ["Tomga mahkamlash konstruksiyalari", "Invertorni tarmoqqa ulash", "Monitoring"] },
      stage4: { period: "1–2 yil", title: "Katta quyosh fermalari", items: ["Megavatt quvvatli stansiyalar", "Yashil energiya sertifikatlari"] }
    },
    educationPath: "TDTU Yashil energetika fakulteti, Samarqand Davlat Universiteti",
    futureOutlook: "O‘zbekistonda 300+ quyoshli kun bor. Bu davlatning strategik ustuvor sohasi.",
    relatedCareers: ["Electrical Engineer", "Ecologist", "Civil Engineer"],
    weightTech: 45,
    weightMed: 0,
    weightEng: 90,
    weightSoc: 15,
    weightCre: 20,
    weightBus: 40,
    weightNat: 85,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-eng-5",
    slug: "welder",
    nameUz: "Payvandchi (Master Welder)",
    nameKrill: "Пайвандчи (Master Welder)",
    nameRu: "Электрогазосварщик",
    nameEn: "Master Welder",
    category: "Construction",
    imageUrl: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Metall konstruksiyalar, neft-gaz quvurlari va ko‘priklarni mustahkam va benuqson choklar bilan birlashtiruvchi usta hunarmand.",
    descriptionKrill: "Металл конструкциялар, нефть-газ қувурлари ва кўприкларни мустаҳкам ва бенуқсон чоклар билан бирлаштирувчи уста ҳунарманд.",
    descriptionRu: "Соединяет металлические узлы, трубопроводы высокого давления и металлоконструкции методами TIG/MIG/MMA.",
    descriptionEn: "Fuses metals via precision arc welding, TIG, MIG, and high-pressure pipeline joint crafting.",
    skills: ["TIG / MIG / MAG / MMA payvandlash", "Metallurgiya asoslari", "Chok sifati nazorati", "Xavfsizlik qoidalari"],
    subjects: ["Fizika", "Mehnat", "Kimyo"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Elektr yoy asoslari", items: ["Elektrodlar turlari", "Payvandlash apparatini sozlash", "Oddiy metallarni ulash"] },
      stage2: { period: "3–6 oy", title: "Argon & Yarim avtomat", items: ["Argon-dugovoy (TIG)", "Zanglamas po'lat bilan ishlash", "Turli burchakli choklar"] },
      stage3: { period: "6–12 oy", title: "Bosimli quvurlar", items: ["Rentgen nazoratidan o'tuvchi chok", "Quvurlarni payvandlash", "Sertifikat olish"] },
      stage4: { period: "1–2 yil", title: "Oliy toifali usta", items: ["Xalqaro payvandlash kodi (ASME/ISO)", "Sanoat montaji"] }
    },
    educationPath: "Kasb-hunar maktablari, Monomarkazlar, Germaniya standartidagi ta'lim markazlari",
    futureOutlook: "Yuqori malakali argon payvandchilarga dunyo va O‘zbekiston sanoatida maosh juda yuqori.",
    relatedCareers: ["Civil Engineer", "Auto Mechanic", "Carpenter"],
    weightTech: 10,
    weightMed: 0,
    weightEng: 85,
    weightSoc: 0,
    weightCre: 25,
    weightBus: 15,
    weightNat: 0,
    weightLaw: 5,
    active: true
  }
];
