import { Career } from '../../src/types';

export const EDU_SOC_CAREERS: Career[] = [
  {
    id: "car-edu-1",
    slug: "math-teacher",
    nameUz: "Matematika Fani O‘qituvchisi",
    nameKrill: "Математика Фани Ўқитувчиси",
    nameRu: "Учитель математики",
    nameEn: "Mathematics Teacher",
    category: "Education",
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Yoshlarga mantiqiy fikrlash, geometriya va algebra sirlarini qiziqarli o‘rgatuvchi, kelajak muhandis va olimlarini tarbiyalovchi ustoz.",
    descriptionKrill: "Ёшларга мантиқий фикрлаш, геометрия ва алгебра сирларини қизиқарли ўргатувчи, келажак муҳандис ва олимларини тарбияловчи устоз.",
    descriptionRu: "Обучает школьников логическому мышлению, алгебре и геометрии, открывая дорогу в точные науки.",
    descriptionEn: "Instructs students in mathematical reasoning, algebra, calculus, and geometrical theorems.",
    skills: ["Pedagogik mahorat", "Olimpiada masalalari", "Sinfni boshqarish", "Individual yondashuv"],
    subjects: ["Matematika", "Geometriya", "Pedagogika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Matematik baza", items: ["Maktab dasturi chuqur", "Mantiqiy jumboqlar", "Pedagogika asoslari"] },
      stage2: { period: "3–6 oy", title: "O'qitish metodikasi", items: ["Interaktiv dars o'tish", "Doska va ko'rgazmali qurollar", "Baholash mezonlari"] },
      stage3: { period: "6–12 oy", title: "Olimpiadalarga tayyorlash", items: ["Xalqaro olimpiada masalalari", "Iqtidorli bolalar bilan ishlash", "Dars ishlanmalari"] },
      stage4: { period: "1–2 yil", title: "Pedagogika OTM", items: ["Nizomiy nomidagi Toshkent Davlat Pedagogika Universiteti (TDPU)"] }
    },
    educationPath: "Nizomiy nomidagi TDPU, O‘zMU Matematika fakulteti, Namangan Davlat Universiteti",
    futureOutlook: "Maktablar, ixtisoslashtirilgan maktablar va o‘quv markazlarida doimiy talabgir.",
    relatedCareers: ["Computer Science Teacher", "Financial Analyst", "Data Analyst"],
    weightTech: 30,
    weightMed: 0,
    weightEng: 20,
    weightSoc: 95,
    weightCre: 30,
    weightBus: 25,
    weightNat: 0,
    weightLaw: 15,
    active: true
  },
  {
    id: "car-edu-2",
    slug: "english-teacher",
    nameUz: "Ingliz Tili O‘qituvchisi (IELTS Instruktor)",
    nameKrill: "Инглиз Тили Ўқитувчиси (IELTS Инструктор)",
    nameRu: "Преподаватель английского языка",
    nameEn: "English Language Teacher / IELTS Instructor",
    category: "Education",
    imageUrl: "https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "O‘quvchilarga dunyo eshiklarini ochuvchi global tilni — so‘zlashuv, grammatika va xalqaro testlarga (IELTS/CEFR) tayyorlovchi zamonaviy murabbiy.",
    descriptionKrill: "Ўқувчиларга дунё эшикларини очувчи глобал тилни — сўзлашув, грамматика ва халқаро тестларга (IELTS/CEFR) тайёрловчи замонавий мураббий.",
    descriptionRu: "Преподает разговорный и академический английский, готовит к международным экзаменам IELTS/TOEFL.",
    descriptionEn: "Coaches students in English fluency, academic writing, and prepares candidates for IELTS/TOEFL certifications.",
    skills: ["IELTS 7.5+", "Interaktiv speaking metodlari", "Kommunikatsiya", "Dars taqdimotlari"],
    subjects: ["Ingliz tili", "Ona tili", "Adabiyot"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Ingliz tili B2/C1", items: ["Grammatika tizimi", "Talaffuz (Phonetics)", "Lug'at boyligi (Vocabulary)"] },
      stage2: { period: "3–6 oy", title: "IELTS tayyorgarlik", items: ["Speaking, Listening, Reading, Writing", "IELTS 7.5+ sertifikat olish", "TKT/TESOL sertifikatlari"] },
      stage3: { period: "6–12 oy", title: "Dars metodikasi", items: ["Communicative Language Teaching", "O'yinli darslar", "Online platformalarda o'qitish"] },
      stage4: { period: "1–2 yil", title: "O'zbekiston Davlat Jahon Tillari Universiteti", items: ["O'zDJTU yoki Webster University diplom"] }
    },
    educationPath: "O‘zbekiston Davlat Jahon Tillari Universiteti (O‘zDJTU), Webster University in Tashkent",
    futureOutlook: "O‘zbekistonda yoshlarning chet tillarini o‘rganishga bo‘lgan talabi eng yuqori cho‘qqida.",
    relatedCareers: ["Math Teacher", "Tourism Guide", "Journalist"],
    weightTech: 20,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 95,
    weightCre: 55,
    weightBus: 60,
    weightNat: 0,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-edu-3",
    slug: "school-psychologist",
    nameUz: "Maktab Psixologi",
    nameKrill: "Мактаб Психологи",
    nameRu: "Школьный психолог",
    nameEn: "School & Child Psychologist",
    category: "Education",
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "O‘quvchilarning qiziqishlari, ruhiy kechinmalari, do‘stlar va ota-onalar bilan munosabatlarini yaxshilashga yordam beruvchi qalb shifokori.",
    descriptionKrill: "Ўқувчиларнинг қизиқишлари, руҳий кечинмалари, дўстлар ва ота-оналар билан муносабатларини яхшилашга ёрдам берувчи қалб шифокори.",
    descriptionRu: "Помогает детям преодолевать эмоциональные кризисы, стрессы перед экзаменами и раскрывать потенциал.",
    descriptionEn: "Assists adolescent mental wellbeing, conducts psycho-evaluations, and resolves behavioral and classroom stress.",
    skills: ["Psixologik diagnostika", "Empatiya & tinglash", "Art-terapiya", "Konfliktlarni yumshatish"],
    subjects: ["Psixologiya", "Biologiya", "Adabiyot", "Ona tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Psixologiya asoslari", items: ["Yosh davrlari psixologiyasi", "Temperament turlari", "Faol tinglash texnikasi"] },
      stage2: { period: "3–6 oy", title: "Diagnostika testlari", items: ["Kasbiy yo'naltirish testlari", "Xavotirlilik darajasi (Spilberger)", "Sotsiometriya"] },
      stage3: { period: "6–12 oy", title: "Konsultatsiya", items: ["Kognitiv-xulqiy terapiya asoslari", "Ota-onalar bilan suhbat", "Art-terapiya mashg'ulotlari"] },
      stage4: { period: "1–2 yil", title: "Diplomli psixolog", items: ["O'zMU Psixologiya fakulteti", "Klinik psixologiya amaliyoti"] }
    },
    educationPath: "O‘zbekiston Milliy Universiteti (O‘zMU) Ijtimoiy fanlar fakulteti, TDPU",
    futureOutlook: "Zamonaviy jamiyatda ruhiy salomatlik va kasbiy yo‘naltirish mutaxassislariga hurmat juda ortib bormoqda.",
    relatedCareers: ["General Doctor", "Career Counselor", "Social Worker"],
    weightTech: 10,
    weightMed: 45,
    weightEng: 0,
    weightSoc: 100,
    weightCre: 40,
    weightBus: 20,
    weightNat: 5,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-law-1",
    slug: "lawyer",
    nameUz: "Huquqshunos / Advokat",
    nameKrill: "Ҳуқуқшунос / Адвокат",
    nameRu: "Юрист / Адвокат",
    nameEn: "Lawyer / Attorney",
    category: "Law",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Fuqarolar va bizneslarning qonuniy manfaatlarini sudda himoya qiluvchi, shartnomalar tuzuvchi va adolat posboni bo‘lgan huquq ustasi.",
    descriptionKrill: "Фуқаролар ва бизнесларнинг қонуний манфаатларини судда ҳимоя қилувчи, шартномалар тузувчи ва адолат посбони бўлган ҳуқуқ устаси.",
    descriptionRu: "Защищает права граждан и бизнеса в суде, составляет договоры и консультирует по правовым вопросам.",
    descriptionEn: "Defends client rights in litigation courts, drafts contractual agreements, and provides statutory counsel.",
    skills: ["Qonunchilik tahlili", "Nutq madaniyati & Ritorika", "Sudda himoya", "Yuridik hujjatlar"],
    subjects: ["Huquq", "Tarix", "Ona tili va adabiyot"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Qonunlar asoslari", items: ["O'zbekiston Konstitutsiyasi", "Fuqarolik va Mehnat kodekslari", "Yuridik atamalar"] },
      stage2: { period: "3–6 oy", title: "Sud amaliyoti", items: ["Sud majlisi tartibi", "Da'vo arizalari yozish", "Notariat qoidalari"] },
      stage3: { period: "6–12 oy", title: "Shartnoma huquqi", items: ["Biznes shartnomalari", "Korporativ huquq", "Advokatlik amaliyoti"] },
      stage4: { period: "1–2 yil", title: "Yuridik universitet", items: ["Toshkent Davlat Yuridik Universiteti (TDYU)", "Advokatlik litsenziyasi"] }
    },
    educationPath: "Toshkent Davlat Yuridik Universiteti (TDYU), JIDU Xalqaro huquq fakulteti",
    futureOutlook: "Qonun ustuvor davlatda advokat va korporativ yuristlar eng obro‘li mutaxassislar qatoridadir.",
    relatedCareers: ["Judge / Prosecutor", "Investigator", "Entrepreneur"],
    weightTech: 10,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 65,
    weightCre: 25,
    weightBus: 60,
    weightNat: 0,
    weightLaw: 100,
    active: true
  },
  {
    id: "car-law-2",
    slug: "investigator",
    nameUz: "Tergovchi / Kriminalist",
    nameKrill: "Терговчи / Криминалист",
    nameRu: "Следователь-криминалист",
    nameEn: "Criminal Investigator / Forensic Specialist",
    category: "Security",
    imageUrl: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Jinoyatlarning sabablarini mantiqiy dalillar, barmoq izlari va ekspertizalar yordamida fosh etuvchi, haqiqatni yuzaga chiqaruvchi jasur xodim.",
    descriptionKrill: "Жиноятларнинг сабабларини мантиқий далиллар, бармоқ излари ва экспертизалар ёрдамида фош этувчи, ҳақиқатни юзага чиқарувчи жасур ходим.",
    descriptionRu: "Расследует обстоятельства преступлений, собирает улики, проводит криминалистические экспертизы.",
    descriptionEn: "Gathers forensic evidence, interviews witnesses, solves complex crime investigations, and upholds justice.",
    skills: ["Kriminalistika", "Deduktiv mantiq", "So'roq o'tkazish psixologiyasi", "Jinoyat-protsessual qoidalari"],
    subjects: ["Huquq", "Tarix", "Kimyo", "Jismoniy tarbiya"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Jinoyat kodeksi", items: ["Jinoyat huquqi asoslari", "Dalillar tushunchasi", "Kriminalistik texnika"] },
      stage2: { period: "3–6 oy", title: "Voqea joyini ko'zdan kechirish", items: ["Daktiloskopiya (barmoq izi)", "Fotofiksatsiya", "Bayonnoma tuzish"] },
      stage3: { period: "6–12 oy", title: "Tergov taktikasi", items: ["Guvohlarni so'roq qilish", "Yuzlashtirish o'tkazish", "Ekspertizalar tayinlash"] },
      stage4: { period: "1–2 yil", title: "IIV Akademiyasi", items: ["O'zbekiston Respublikasi IIV Akademiyasi", "Bosh prokuratura akademiyasi"] }
    },
    educationPath: "O‘zbekiston Respublikasi IIV Akademiyasi, Huquqni muhofaza qilish akademiyasi",
    futureOutlook: "Davlat xavfsizligi, adolat va tinchlikni ta'minlashda mas'uliyatli va sharafli kasb.",
    relatedCareers: ["Lawyer", "Cybersecurity Specialist", "Judge / Prosecutor"],
    weightTech: 30,
    weightMed: 20,
    weightEng: 10,
    weightSoc: 30,
    weightCre: 20,
    weightBus: 10,
    weightNat: 0,
    weightLaw: 100,
    active: true
  },
  {
    id: "car-bus-1",
    slug: "entrepreneur",
    nameUz: "Tadbirkor / Biznes Asoschisi (Entrepreneur)",
    nameKrill: "Тадбиркор / Бизнес Асосчиси (Entrepreneur)",
    nameRu: "Предприниматель / Основатель бизнеса",
    nameEn: "Entrepreneur / Business Founder",
    category: "Business",
    imageUrl: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Yangi g‘oyalarni amalga oshirib, korxona va ish o‘rinlari yaratuvchi, tavakkalchilikdan qo‘rqmaydigan zamonaviy yetakchi.",
    descriptionKrill: "Янги ғояларни амалга ошириб, корхона ва иш ўринлари яратувчи, таваккалчиликдан қўрқмайдиган замонавий етакчи.",
    descriptionRu: "Создает новые коммерческие предприятия, нанимает команду, привлекает инвестиции и управляет рисками.",
    descriptionEn: "Launches dynamic enterprises, assembles high-performing teams, raises capital, and creates jobs.",
    skills: ["Yetakchilik & Biznes reja", "Moliyaviy savodxonlik", "Muzokaralar olib borish", "Tavakkalchilikni boshqarish"],
    subjects: ["Iqtisodiyot", "Matematika", "Ingliz tili", "Huquq"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "G'oya va Bozor", items: ["Bozor ehtiyojini topish", "Biznes-reja tuzish", "Raqobatchilarni tahlil qilish"] },
      stage2: { period: "3–6 oy", title: "Moliya & Huquq", items: ["Boshlang'ich kapital hisobi", "YTT yoki MCHJ ochish", "Soliq turlari"] },
      stage3: { period: "6–12 oy", title: "Savdo va Jamoa", items: ["Birinchi mijozlarni jalb qilish", "Sotuv bo'limini qurish", "Kadrlar tanlash"] },
      stage4: { period: "1–2 yil", title: "Masshtablash", items: ["Filiallar ochish", "Avtomatlashtirish", "Xalqaro bozorga chiqish"] }
    },
    educationPath: "TDIU, TEAM University, Singapur menejmentni rivojlantirish instituti (MDIST)",
    futureOutlook: "O‘zbekiston iqtisodiyoti drayveri tadbirkorlik hisoblanadi. Imkoniyatlar cheksiz.",
    relatedCareers: ["Product Manager", "Marketing Specialist", "Financial Analyst"],
    weightTech: 35,
    weightMed: 0,
    weightEng: 20,
    weightSoc: 50,
    weightCre: 65,
    weightBus: 100,
    weightNat: 0,
    weightLaw: 35,
    active: true
  },
  {
    id: "car-bus-2",
    slug: "financial-analyst",
    nameUz: "Moliyaviy Tahlilchi / Auditor",
    nameKrill: "Молиявий Таҳлилчи / Аудитор",
    nameRu: "Финансовый аналитик / Аудитор",
    nameEn: "Financial Analyst / Auditor",
    category: "Finance",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Kompaniya daromadlarini tahlil qiluvchi, aksiyalar, investitsiya va moliyaviy xatarlarni baholab, kapitalni ko‘paytiruvchi mutaxassis.",
    descriptionKrill: "Компания даромадларини таҳлил қилувчи, акциялар, инвестиция ва молиявий хатарларни баҳолаб, капитални кўпайтирувчи мутахассис.",
    descriptionRu: "Оценивает рентабельность инвестиций, финансовые отчетности компаний и минимизирует финансовые риски.",
    descriptionEn: "Evaluates balance sheets, corporate cashflows, portfolio risk allocations, and investment viability.",
    skills: ["Moliyaviy modellashtirish", "ACCA / CFA asoslari", "Buxgalteriya 1C", "Excel chuqur daraja"],
    subjects: ["Matematika", "Iqtisodiyot", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Buxgalteriya asoslari", items: ["Debit va Kredit", "Moliyaviy hisobotlar (Balans, Foyda/Zarar)", "Excel formulalari"] },
      stage2: { period: "3–6 oy", title: "Moliya tahlili", items: ["Rentabellik koeffitsiyentlari", "Cash Flow tahlili", "EBITDA hisobi"] },
      stage3: { period: "6–12 oy", title: "Investitsiya & Bozor", items: ["Aksiya va obligatsiyalar", "DCF modellashtirish", "ACCA imtihonlariga kirish"] },
      stage4: { period: "1–2 yil", title: "Xalqaro sertifikatlar", items: ["ACCA / CFA dasturlari", "Banklar yoki audit kompaniyalari (Big 4)"] }
    },
    educationPath: "Toshkent Moliya Instituti, Xalqaro Vestminster Universiteti (WIUT), TDIU",
    futureOutlook: "Banklar, sug‘urta kompaniyalari va yirik xoldinglarda eng nufuzli kasblardan biri.",
    relatedCareers: ["Data Analyst", "Entrepreneur", "Accountant"],
    weightTech: 40,
    weightMed: 0,
    weightEng: 0,
    weightSoc: 25,
    weightCre: 15,
    weightBus: 100,
    weightNat: 0,
    weightLaw: 45,
    active: true
  },
  {
    id: "car-cre-1",
    slug: "ui-ux-designer",
    nameUz: "UI/UX Dizayner (Product Designer)",
    nameKrill: "UI/UX Дизайнер (Product Designer)",
    nameRu: "UI/UX Дизайнер",
    nameEn: "UI/UX Product Designer",
    category: "Creative",
    imageUrl: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Ilova va saytlarning insonlarga tushunarli, qulay va ko‘zga yoqimli bo‘lishini tadqiqotlar va chiroyli dizayn orqali yaratuvchi ijodkor.",
    descriptionKrill: "Илова ва сайтларнинг инсонларга тушунарли, қулай ва кўзга ёқимли бўлишини тадқиқотлар ва чиройли дизайн орқали яратувчи ижодкор.",
    descriptionRu: "Проектирует пользовательский опыт (UX) и эстетичный визуальный интерфейс (UI) цифровых сервисов.",
    descriptionEn: "Researches user behavior, maps intuitive navigation journeys, and crafts pixel-perfect interface visuals.",
    skills: ["Figma", "User Research & Testing", "Dizayn tizimlari (Design Systems)", "Tipografika & Ranglar"],
    subjects: ["Tasviriy san'at", "Informatika", "Psixologiya", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Figma & Dizayn asoslari", items: ["Figma asboblari va Auto-layout", "Ranglar uyg'unligi", "Tipografika qoidalari"] },
      stage2: { period: "3–6 oy", title: "UX tadqiqot", items: ["User Persona yaratish", "CJM (Customer Journey Map)", "Wireframe eskizlar"] },
      stage3: { period: "6–12 oy", title: "Interaktiv prototip", items: ["Komponentlar va variantlar", "Dizayn tizimi (Design System)", "Behance portfolio"] },
      stage4: { period: "1–2 yil", title: "Senior darajaga o'tish", items: ["Dasturchilar bilan ishlash", "A/B testlar o'tkazish", "Micro-animations"] }
    },
    educationPath: "Kamoliddin Behzod nomidagi Milliy rassomlik va dizayn instituti, IT Park",
    futureOutlook: "Har bir dastur va sayt muvaffaqiyati uning dizayniga bog‘liq. Juda yuqori talabli kasb.",
    relatedCareers: ["Frontend Developer", "Graphic Designer", "Product Manager"],
    weightTech: 65,
    weightMed: 0,
    weightEng: 15,
    weightSoc: 50,
    weightCre: 100,
    weightBus: 45,
    weightNat: 0,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-cre-2",
    slug: "executive-chef",
    nameUz: "Bosh Oshpaz (Executive Chef)",
    nameKrill: "Бош Ошпаз (Executive Chef)",
    nameRu: "Шеф-повар",
    nameEn: "Executive Chef / Master Culinary Artist",
    category: "Food",
    imageUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Milliy va jahon taomlarini yuqori mahorat bilan tayyorlovchi, yangi retseptlar kashf qilib restoranga rahbarlik qiluvchi lazzat dahosi.",
    descriptionKrill: "Миллий ва жаҳон таомларини юқори маҳорат билан тайёрловчи, янги рецептлар кашф қилиб ресторанга раҳбарлик қилувчи лаззат даҳоси.",
    descriptionRu: "Создает авторские кулинарные меню, организует работу ресторанной кухни и превращает еду в искусство.",
    descriptionEn: "Orchestrates fine dining kitchens, innovates gastronomic recipes, and delivers supreme culinary creations.",
    skills: ["Kulinariya san'ati", "Oshxona boshqaruvi", "Oziq-ovqat xavfsizligi (HACCP)", "Taomlarni estetik bezatish"],
    subjects: ["Mehnat ta'limi", "Kimyo", "Biologiya"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Oshpazlik asoslari", items: ["Pichoq bilan professional ishlash", "Sanitariya qoidalari", "Milliy taomlar tayyorlash"] },
      stage2: { period: "3–6 oy", title: "Yevropa & Osiyo taomlari", items: ["Souslar tayyorlash", "Go'sht va baliqni to'g'ri pishirish", "Issiq va sovuq taomlar"] },
      stage3: { period: "6–12 oy", title: "Menyu va Tanqislik", items: ["Mualliflik menyusi tuzish", "Kalkulyatsiya va tannarx", "Restoran jamoasini boshqarish"] },
      stage4: { period: "1–2 yil", title: "Master Chef daraja", items: ["Xalqaro oshpazlik sertifikatlari", "Mishelin restoranlari amaliyoti"] }
    },
    educationPath: "Xizmat ko‘rsatish va servis texnikumlari, Xalqaro oshpazlik akademiyalari",
    futureOutlook: "Turizm, to‘yxonalar va restoran biznesi jadal rivojlanayotgan O‘zbekistonda doimiy qadrli kasb.",
    relatedCareers: ["Pastry Chef", "Hotel Manager", "Entrepreneur"],
    weightTech: 0,
    weightMed: 15,
    weightEng: 10,
    weightSoc: 40,
    weightCre: 85,
    weightBus: 60,
    weightNat: 30,
    weightLaw: 10,
    active: true
  }
];
