import { Career } from '../../src/types';

export const MEDICAL_CAREERS: Career[] = [
  {
    id: "car-med-1",
    slug: "general-doctor",
    nameUz: "Umumiy Amaliyot Shifokori (Terapevt)",
    nameKrill: "Умумий Амалиёт Шифокори (Терапевт)",
    nameRu: "Врач общей практики (Терапевт)",
    nameEn: "General Practitioner / Internist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Kattalar va oila a'zolarining umumiy sog‘lig‘ini nazorat qiluvchi, kasalliklarni dastlabki bosqichda aniqlab, davolovchi fidoyi mutaxassis.",
    descriptionKrill: "Катталар ва оила аъзоларининг умумий соғлиғини назорат қилувчи, касалликларни дастлабки босқичда аниқлаб, даволовчи фидойи мутахассис.",
    descriptionRu: "Первичный диагност здоровья пациентов, подбирает медикаментозное лечение и направляет к узким специалистам.",
    descriptionEn: "Evaluates patient health, diagnoses multi-system ailments, prescribes therapy, and coordinates specialized care.",
    skills: ["Klinik diagnostika", "Bemor bilan muloqot", "Farmakoterapiya", "Tibbiy etika"],
    subjects: ["Biologiya", "Kimyo", "Ona tili", "Lotin tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Biologiya & Kimyo", items: ["Odam anatomiyasi", "Organik kimyo asoslari", "Lotin tili atamalari"] },
      stage2: { period: "3–6 oy", title: "Fiziologiya", items: ["Organlar ishlash mexanizmi", "Qon va aylanma tizimi", "Laboratoriya tahlillari"] },
      stage3: { period: "6–12 oy", title: "Klinik asoslar", items: ["Simptomatika", "Dori vositalari farmakologiyasi", "Kasalxona amaliyoti"] },
      stage4: { period: "1–2 yil", title: "Tibbiyot oliygohi", items: ["Davolash ishi fakulteti (6 yil)", "Klinik ordinatura", "Shifokor litsenziyasi"] }
    },
    educationPath: "Toshkent Tibbiyot Akademiyasi (TTA), Samarqand Davlat Tibbiyot Universiteti, Andijon Davlat Tibbiyot Instituti",
    futureOutlook: "Insoniyat bor ekan, shifokorlik jamiyatning eng oliy va hurmatli ehtiyoji bo‘lib qoladi.",
    relatedCareers: ["Pediatrician", "Cardiologist", "Neurologist"],
    weightTech: 10,
    weightMed: 100,
    weightEng: 0,
    weightSoc: 70,
    weightCre: 10,
    weightBus: 15,
    weightNat: 20,
    weightLaw: 15,
    active: true
  },
  {
    id: "car-med-2",
    slug: "surgeon",
    nameUz: "Jarroh (Surgeon)",
    nameKrill: "Жарроҳ (Surgeon)",
    nameRu: "Хирург (Surgeon)",
    nameEn: "Surgeon",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Murakkab operatsiyalarni o‘tkazib, inson hayotini to‘g‘ridan-to‘g‘ri saqlab qoluvchi, temir irodali va nozik qo‘l harakatiga ega bo‘lgan mohir mutaxassis.",
    descriptionKrill: "Мураккаб операцияларни ўтказиб, инсон ҳаётини тўғридан-тўғри сақлаб қолувчи, темир иродали ва нозик қўл ҳаракатига эга бўлган моҳир мутахассис.",
    descriptionRu: "Проводит оперативные вмешательства, спасая жизни в экстренных и плановых хирургических ситуациях.",
    descriptionEn: "Performs surgical interventions, requiring immense mental composure, deep anatomy mastery, and manual dexterity.",
    skills: ["Jarrohlik texnikasi", "Favqulodda qaror qabul qilish", "Anatomiya chuqur bilimi", "Charchoqqa chidamlilik"],
    subjects: ["Biologiya", "Kimyo", "Fizika", "Lotin tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Anatomiya", items: ["Topografik anatomiya", "Hujayra va to'qimalar", "Aseptika va antiseptika"] },
      stage2: { period: "3–6 oy", title: "Operatsion blok", items: ["Jarrohlik asboblari", "Tugunlar bog'lash texnikasi", "Yaralarni tikish"] },
      stage3: { period: "6–12 oy", title: "Pre-operatsiya", items: ["Narkoz asoslari", "Qon quyish qoidalari", "Klinik shifoxona navbatchiligi"] },
      stage4: { period: "1–2 yil", title: "Jarrohlik magistraturasi", items: ["Klinik ordinatura (2-3 yil)", "Mustaqil assistentlik", "Laparoskopik operatsiyalar"] }
    },
    educationPath: "TTA, Respublika Shoshilinch Tibbiy Yordam Ilmiy Markazi (RShTYOIM)",
    futureOutlook: "Tibbiyotning eng mas'uliyatli va eng yuqori ehtiromga ega sohalaridan biri.",
    relatedCareers: ["Cardiologist", "Orthopedist", "Anesthesiologist"],
    weightTech: 20,
    weightMed: 100,
    weightEng: 15,
    weightSoc: 65,
    weightCre: 25,
    weightBus: 10,
    weightNat: 15,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-med-3",
    slug: "pediatrician",
    nameUz: "Bolalar Shifokori (Pediatr)",
    nameKrill: "Болалар Шифокори (Педиатр)",
    nameRu: "Врач-педиатр",
    nameEn: "Pediatrician",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Chaqaloqlar va bolalarning jismoniy rivojlanishini kuzatuvchi, bolalarga mehr bilan munosabatda bo‘lib ularni davolovchi shifokor.",
    descriptionKrill: "Чақалоқлар ва болаларнинг жисмоний ривожланишини кузатувчи, болаларга меҳр билан муносабатда бўлиб уларни даволовчи шифокор.",
    descriptionRu: "Специализируется на здоровье, гармоничном развитии и лечении заболеваний новорожденных и детей.",
    descriptionEn: "Monitors child growth, administers immunizations, and treats infant and adolescent health conditions.",
    skills: ["Bolalar psixologiyasi", "Emlash taqvimi", "Bolalar diagnostikasi", "Sabr-toqat va mehr"],
    subjects: ["Biologiya", "Kimyo", "Pedagogika", "Ona tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Rivojlanish asoslari", items: ["Yosh fiziologiyasi", "Chaqaloqlar parvarishi", "Bolalar ovqatlanishi"] },
      stage2: { period: "3–6 oy", title: "Pediatrik patologiya", items: ["Bolalar yuqumli kasalliklari", "Emlash sxemalari", "Isitmani tushirish"] },
      stage3: { period: "6–12 oy", title: "Amaliy ko'nikmalar", items: ["Bolalar bilan muloqot", "Shoshilinch bolalar yordami", "Ota-onalar bilan ishlash"] },
      stage4: { period: "1–2 yil", title: "Pediatriya OTM", items: ["Toshkent Pediatriya Tibbiyot Instituti (SamPI)", "Pediatrik ordinatura"] }
    },
    educationPath: "Toshkent Pediatriya Tibbiyot Instituti (ToshPTI), viloyat tibbiyot institutlari",
    futureOutlook: "O‘zbekiston aholisi yosh bo‘lgani sababli pediatr shifokorlarga talab doim favqulodda yuqori.",
    relatedCareers: ["General Doctor", "Child Psychologist", "Nurse"],
    weightTech: 5,
    weightMed: 98,
    weightEng: 0,
    weightSoc: 90,
    weightCre: 25,
    weightBus: 10,
    weightNat: 15,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-med-4",
    slug: "dentist",
    nameUz: "Stomatolog (Tish Shifokori)",
    nameKrill: "Стоматолог (Тиш Шифокори)",
    nameRu: "Врач-стоматолог",
    nameEn: "Dentist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Tishlar, milklar va og‘iz bo‘shlig‘i salomatligini saqlovchi, chiroyli tabassum va estetikani yaratuvchi tibbiyot mutaxassisi.",
    descriptionKrill: "Тишлар, милклар ва оғиз бўшлиғи саломатлигини сақловчи, чиройли табассум ва эстетикани яратувчи тиббиёт мутахассиси.",
    descriptionRu: "Лечит заболевания зубов и десен, восстанавливает эстетику улыбки, устанавливает импланты и пломбы.",
    descriptionEn: "Treats dental issues, caries, root canals, implants, and crafts aesthetic smile restoration.",
    skills: ["Stomatologik uskunalar", "Anesteziya", "Estetik plomba", "Ortodontiya asoslari"],
    subjects: ["Biologiya", "Kimyo", "Fizika", "Tasviriy san'at"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Tish anatomiyasi", items: ["Tishlar tuzilishi", "Karies va asoratlar", "Sterilizatsiya qoidalari"] },
      stage2: { period: "3–6 oy", title: "Materialshunoslik", items: ["Plomba materiallari", "Zamonaviy kompozitlar", "Tish rentgeni"] },
      stage3: { period: "6–12 oy", title: "Klinik amaliyot", items: ["Fantoma kurslari", "Tish tozalash va oqartirish", "Kanal davolash"] },
      stage4: { period: "1–2 yil", title: "Oliy stomatologiya", items: ["Toshkent Davlat Stomatologiya Instituti (TDSI)", "Implantologiya", "Ortodontiya"] }
    },
    educationPath: "Toshkent Davlat Stomatologiya Instituti (TDSI), viloyat tibbiyot institutlari stomatologiya fakulteti",
    futureOutlook: "Doimiy daromadli, xususiy klinika ochish imkoniyati keng va talabi barqaror kasb.",
    relatedCareers: ["Surgeon", "General Doctor", "Orthopedist"],
    weightTech: 25,
    weightMed: 95,
    weightEng: 20,
    weightSoc: 60,
    weightCre: 50,
    weightBus: 60,
    weightNat: 10,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-med-5",
    slug: "cardiologist",
    nameUz: "Kardiolog (Yurak Shifokori)",
    nameKrill: "Кардиолог (Юрак Шифокори)",
    nameRu: "Врач-кардиолог",
    nameEn: "Cardiologist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Yurak va qon tomirlari kasalliklarini, infarkt va gipertoniyani chuqur tekshirib davolovchi yuqori malakali shifokor.",
    descriptionKrill: "Юрак ва қон томирлари касалликларини, инфаркт ва гипертонияни чуқур текшириб даволовчи юқори малакали шифокор.",
    descriptionRu: "Диагностирует заболевания сердечно-сосудистой системы, расшифровывает ЭКГ и предотвращает инфаркты.",
    descriptionEn: "Specializes in heart and cardiovascular disorders, reads ECGs, conducts angioplasty, and saves cardiac patients.",
    skills: ["EKG va ExoKG tahlili", "Qon bosimi monitoringi", "Kardiologik dori-darmonlar", "Shoshilinch reanimatsiya"],
    subjects: ["Biologiya", "Kimyo", "Fizika", "Matematika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Yurak anatomiyasi", items: ["Yurak kameralari va klapanlari", "Kardio-fiziologiya", "Qon aylanish doiralari"] },
      stage2: { period: "3–6 oy", title: "EKG asoslari", items: ["EKG tishchalari", "Aritmiyalarni aniqlash", "Ishemiya belgilari"] },
      stage3: { period: "6–12 oy", title: "Kardioterapiya", items: ["Antihipertenziv dorilar", "Xolesterin va ateroskleroz", "Stentlash haqida tushuncha"] },
      stage4: { period: "1–2 yil", title: "Respublika Kardiologiya", items: ["Kardiologiya ilmiy markazi ordinaturasi", "Angiografiya amaliyoti"] }
    },
    educationPath: "TTA, Respublika Ixtisoslashtirilgan Kardiologiya Ilmiy-Amaliy Tibbiyot Markazi (RIKIATTM)",
    futureOutlook: "Yurak-qon tomir kasalliklari global miqyosda 1-o‘rinda turadi, kardiologlar doim qadrlanadi.",
    relatedCareers: ["Surgeon", "General Doctor", "Radiologist"],
    weightTech: 35,
    weightMed: 100,
    weightEng: 10,
    weightSoc: 65,
    weightCre: 10,
    weightBus: 15,
    weightNat: 15,
    weightLaw: 15,
    active: true
  },
  {
    id: "car-med-6",
    slug: "pharmacist",
    nameUz: "Provizor / Farmatsevt",
    nameKrill: "Провизор / Фармацевт",
    nameRu: "Провизор / Фармацевт",
    nameEn: "Pharmacist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Dori vositalarining kimyoviy tarkibini biluvchi, yangi dori ishlab chiqarish yoki dorixonalarda to‘g‘ri tavsiya etuvchi mutaxassis.",
    descriptionKrill: "Дори воситаларининг кимёвий таркибини билувчи, янги дори ишлаб чиқариш ёки дорихоналарда тўғри тавсия этувчи мутахассис.",
    descriptionRu: "Эксперт по лекарственным препаратам, их взаимодействию, дозировкам и фармацевтическому производству.",
    descriptionEn: "Dispenses prescriptions, formulates medications, and ensures safe chemical interaction between drug treatments.",
    skills: ["Farmakologiya", "Organik va analitik kimyo", "Dori shakllari", "Mijozlarga maslahat"],
    subjects: ["Kimyo", "Biologiya", "Lotin tili", "Matematika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Kimyo va Lotin", items: ["Farmatsevtik lotin tili", "Dori shakllari (tabletkalar, malhamlar)", "Retsept yozish"] },
      stage2: { period: "3–6 oy", title: "Farmakologiya", items: ["Antibiotiklar, vitaminlar", "Nojo'ya ta'sirlar", "Dorilar o'zaro ta'siri"] },
      stage3: { period: "6–12 oy", title: "Dori ishlab chiqarish", items: ["Zavod texnologiyalari", "Sifat nazorati (GMP)", "Dorixona iqtisodiyoti"] },
      stage4: { period: "1–2 yil", title: "Farmatsevtika instituti", items: ["Toshkent Farmatsevtika Instituti", "Klinik farmatsiya"] }
    },
    educationPath: "Toshkent Farmatsevtika Instituti (ToshFarMI)",
    futureOutlook: "Farmatsevtika sanoati O‘zbekistonda eng tez o‘sayotgan sanoat tarmoqlaridan biridir.",
    relatedCareers: ["Biotechnologist", "Laboratory Technician", "Chemical Engineer"],
    weightTech: 20,
    weightMed: 92,
    weightEng: 10,
    weightSoc: 50,
    weightCre: 15,
    weightBus: 60,
    weightNat: 30,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-med-7",
    slug: "biotechnologist",
    nameUz: "Biotexnolog",
    nameKrill: "Биотехнолог",
    nameRu: "Биотехнолог",
    nameEn: "Biotechnologist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Genetika, mikroorganizmlar va tirik hujayralardan foydalanib vaksinalar, oziq-ovqat va yangi dorilar yaratuvchi zamonaviy olim.",
    descriptionKrill: "Генетика, микроорганизмлар ва тирик ҳужайралардан фойдаланиб вакциналар, озиқ-овқат ва янги дорилар яратувчи замонавий олим.",
    descriptionRu: "Использует живые организмы, микробиологию и ДНК-технологии для создания вакцин и биопрепаратов.",
    descriptionEn: "Manipulates cellular biology and genetic coding to manufacture life-saving vaccines, biosimilars, and enzymes.",
    skills: ["Genetika & DNK tahlili", "Mikrobiologiya", "Bioreaktorlar", "Laboratoriya uskunalari"],
    subjects: ["Biologiya", "Kimyo", "Informatika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Genetika & Hujayra", items: ["Hujayra biologiyasi", "DNK va RNK tuzilishi", "Mikroskopiya"] },
      stage2: { period: "3–6 oy", title: "Mikrobiologiya", items: ["Bakteriyalar kultivatsiyasi", "Fermentlar faolligi", "Steril muhit qoidalari"] },
      stage3: { period: "6–12 oy", title: "Gen injeneriyasi", items: ["PCR tahlili", "Klonlash asoslari", "Bioinformatika vositalari"] },
      stage4: { period: "1–2 yil", title: "Biotexnologiya markazlari", items: ["Ilg'or Texnologiyalar Markazi", "Xalqaro ilmiy loyihalar"] }
    },
    educationPath: "O‘zbekiston Milliy Universiteti (O‘zMU) Biologiya fakulteti, ToshFarMI, New Uzbekistan University",
    futureOutlook: "21-asr — biologiya va biotexnologiyalar asri hisoblanadi. Juda istiqbolli yo‘nalish.",
    relatedCareers: ["Pharmacist", "Laboratory Technician", "Agronomist"],
    weightTech: 50,
    weightMed: 88,
    weightEng: 30,
    weightSoc: 20,
    weightCre: 40,
    weightBus: 35,
    weightNat: 75,
    weightLaw: 15,
    active: true
  },
  {
    id: "car-med-8",
    slug: "ophthalmologist",
    nameUz: "Oftalmolog (Ko‘z Shifokori)",
    nameKrill: "Офтальмолог (Кўз Шифокори)",
    nameRu: "Врач-офтальмолог (Окулист)",
    nameEn: "Ophthalmologist",
    category: "Medicine",
    imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Ko‘z nuri va ko‘rish qobiliyatini saqlovchi, lazerli korreksiya va ko‘z operatsiyalarini amalga oshiruvchi nozik shifokor.",
    descriptionKrill: "Кўз нури ва кўриш қобилиятини сақловчи, лазерли коррекция ва кўз операцияларини амалга оширувчи нозик шифокор.",
    descriptionRu: "Диагностирует зрение, подбирает оптическую коррекцию и выполняет лазерные микрохирургические операции на глазах.",
    descriptionEn: "Diagnoses visual disorders, operates delicate laser micro-surgery, and restores retinal eyesight.",
    skills: ["Ko'z mikroxirurgiyasi", "Optometriya", "Lazer uskunalar", "Nozik barmoq harakatlari"],
    subjects: ["Biologiya", "Fizika (Optika)", "Kimyo"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Ko'z fizikasi & optika", items: ["Nur sinishi qonunlari", "Ko'z anatomiyasi", "Ko'rish o'tkirligi jadvallari"] },
      stage2: { period: "3–6 oy", title: "Ko'z asboblari", items: ["Ofalmoskop bilan tekshirish", "Ko'z ichki bosimi (tonometriya)", "Ko'zoynak tanlash"] },
      stage3: { period: "6–12 oy", title: "Ko'z patologiyasi", items: ["Katarakta va glaukoma", "To'r parda kasalliklari", "Ko'z tomchilari"] },
      stage4: { period: "1–2 yil", title: "Mikroxirurgiya", items: ["Ko'z mikroxirurgiyasi ilmiy markazi", "Lazerli korreksiya (LASIK)"] }
    },
    educationPath: "TTA, Respublika Ko‘z Kasalliklari Klinik Shifoxonasi",
    futureOutlook: "Smartfonlar asrida ko‘z shifokorlariga ehtiyoj har yili ikki barobar oshmoqda.",
    relatedCareers: ["Surgeon", "General Doctor", "Dentist"],
    weightTech: 35,
    weightMed: 95,
    weightEng: 20,
    weightSoc: 60,
    weightCre: 25,
    weightBus: 25,
    weightNat: 10,
    weightLaw: 10,
    active: true
  }
];
