import { Career } from '../../src/types';

export const TECH_CAREERS_PART2: Career[] = [
  {
    id: "car-tech-11",
    slug: "full-stack-developer",
    nameUz: "Full Stack Dasturchi",
    nameKrill: "Full Stack Дастурчи",
    nameRu: "Full Stack Разработчик",
    nameEn: "Full Stack Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Loyiha boshidan oxirigacha — foydalanuvchi ko‘radigan interfeysdan tortib server va ma'lumotlar bazasigacha to‘liq yarata oladigan ko‘p qirrali dasturchi.",
    descriptionKrill: "Лойиҳа бошидан охиригача — фойдаланувчи кўрадиган интерфейсдан тортиб сервер ва маълумотлар базасигача тўлиқ ярата оладиган кўп қиррали дастурчи.",
    descriptionRu: "Универсальный разработчик, создающий и клиентскую визуальную часть, и серверную логику с базой данных.",
    descriptionEn: "Versatile engineer capable of building end-to-end applications across client frontend, server API, and database layers.",
    skills: ["React / Next.js", "Node.js / Express", "PostgreSQL", "REST API", "Docker"],
    subjects: ["Informatika", "Matematika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Web asoslari", items: ["HTML/CSS/JS", "Git & GitHub", "Terminal buyruqlari"] },
      stage2: { period: "3–6 oy", title: "Frontend Framework", items: ["React asoslari", "Tailwind CSS", "API bilan ishlash"] },
      stage3: { period: "6–12 oy", title: "Backend & DB", items: ["Node.js va Express", "PostgreSQL / Prisma ORM", "Autentifikatsiya"] },
      stage4: { period: "1–2 yil", title: "Full Stack deploy", items: ["Vercel / Docker deploy", "State management", "Production amaliyoti"] }
    },
    educationPath: "TATU, Inha, Amity, IT Park",
    futureOutlook: "Startaplar va IT kompaniyalarda eng ko‘p qidiriladigan ko‘p qirrali mutaxassis.",
    relatedCareers: ["Software Developer", "Frontend Developer", "Backend Developer"],
    weightTech: 98,
    weightMed: 0,
    weightEng: 35,
    weightSoc: 20,
    weightCre: 65,
    weightBus: 40,
    weightNat: 0,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-tech-12",
    slug: "qa-engineer",
    nameUz: "Sifat Nazoratchisi (QA / Tester)",
    nameKrill: "Сифат Назоратчиси (QA / Tester)",
    nameRu: "Инженер по тестированию (QA Engineer)",
    nameEn: "Quality Assurance (QA) Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Dastur va ilovalardagi xato va kamchiliklarni foydalanuvchilar ko‘rmasidan oldin aniqlovchi va mahsulot sifatini kafolatlovchi mutaxassis.",
    descriptionKrill: "Дастур ва иловалардаги хато ва камчиликларни фойдаланувчилар кўрмасидан олдин аниқловчи ва маҳсулот сифатини кафолатловчи мутахассис.",
    descriptionRu: "Проверяет корректность работы программного обеспечения, находит скрытые ошибки и составляет тест-кейсы.",
    descriptionEn: "Identifies software bugs, executes automated and manual testing scenarios, and guarantees release stability.",
    skills: ["Qo'lda testlash (Manual)", "Avtotestlash (Playwright / Cypress)", "Bug reporting", "Postman / API testing"],
    subjects: ["Informatika", "Ingliz tili", "Ona tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "QA asoslari", items: ["Testlash nazariyasi", "Bug Report yozish", "Test Case va Check-list"] },
      stage2: { period: "3–6 oy", title: "Web & API testing", items: ["Chrome DevTools", "Postman bilan API tekshirish", "SQL asoslari"] },
      stage3: { period: "6–12 oy", title: "Avtomatlashtirish", items: ["Python yoki JS asoslari", "Selenium / Playwright", "CI/CD integratsiyasi"] },
      stage4: { period: "1–2 yil", title: "Yuklama va Xavfsizlik", items: ["JMeter yuklama testi", "ISTQB sertifikati", "QA Lead ko'nikmalari"] }
    },
    educationPath: "TATU, IT Park kurslari, xalqaro ISTQB sertifikatsiyasi",
    futureOutlook: "Har qanday raqamli loyiha relizidan oldin zarur bo‘lgan muhim rol.",
    relatedCareers: ["Software Developer", "Product Manager", "System Administrator"],
    weightTech: 88,
    weightMed: 0,
    weightEng: 25,
    weightSoc: 25,
    weightCre: 30,
    weightBus: 40,
    weightNat: 0,
    weightLaw: 45,
    active: true
  },
  {
    id: "car-tech-13",
    slug: "network-engineer",
    nameUz: "Tarmoq Muhandisi (Network Engineer)",
    nameKrill: "Тармоқ Муҳандиси (Network Engineer)",
    nameRu: "Сетевой инженер",
    nameEn: "Network Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Optik tolali internet tarmoqlari, router va kommutatorlarni sozlovchi, uzluksiz aloqa infratuzilmasini ta'minlovchi muhandis.",
    descriptionKrill: "Оптик толали интернет тармоқлари, роутер ва коммутаторларни созловчи, узлуксиз алоқа инфратузилмасини таъминловчи муҳандис.",
    descriptionRu: "Проектирует и настраивает локальные и глобальные сети, оптоволоконные линии и маршрутизаторы Cisco/MikroTik.",
    descriptionEn: "Configures routers, switches, enterprise VPNs, and optic-fiber networks ensuring uninterrupted connectivity.",
    skills: ["Cisco CCNA", "MikroTik RouterOS", "IP addressing & Subnetting", "Wi-Fi va Optik tarmoqlar"],
    subjects: ["Fizika", "Informatika", "Ingliz tili", "Matematika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Tarmoq asoslari", items: ["OSI 7 pog'onali model", "IPv4 va IPv6", "Kabel montaji va siqish"] },
      stage2: { period: "3–6 oy", title: "Marshrutlash", items: ["VLAN, STP, OSPF", "MikroTik va Cisco konfiguratsiya", "DHCP, DNS sozlash"] },
      stage3: { period: "6–12 oy", title: "Xavfsizlik", items: ["VPN tunnellari", "Firewall qoidalari", "Tarmoq monitoringi (Zabbix)"] },
      stage4: { period: "1–2 yil", title: "Enterprise daraja", items: ["Cisco CCNP", "BGP marshrutlash", "Data Center tarmoqlari"] }
    },
    educationPath: "TATU Telekommunikatsiya fakulteti, O‘zbektelekom o‘quv markazlari",
    futureOutlook: "5G, optika va milliy internet tizimlari kengayishi hisobiga talab barqaror.",
    relatedCareers: ["System Administrator", "Cybersecurity Specialist", "DevOps Engineer"],
    weightTech: 90,
    weightMed: 0,
    weightEng: 70,
    weightSoc: 10,
    weightCre: 10,
    weightBus: 20,
    weightNat: 0,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-tech-14",
    slug: "system-administrator",
    nameUz: "Tizim Administratori (SysAdmin)",
    nameKrill: "Тизим Администратори (SysAdmin)",
    nameRu: "Системный администратор",
    nameEn: "System Administrator",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Idora va korxonalardagi serverlar, kompyuterlar, printerlar va dasturiy ta'minotlarning soz va xavfsiz ishlashini nazorat qiluvchi mutaxassis.",
    descriptionKrill: "Идора ва корхоналардаги серверлар, компьютерлар, принтерлар ва дастурий таъминотларнинг соз ва хавфсиз ишлашини назорат қилувчи мутахассис.",
    descriptionRu: "Поддерживает работоспособность компьютерного парка, серверов Windows/Linux и офисной техники предприятия.",
    descriptionEn: "Maintains corporate server infrastructure, Active Directory, software deployments, and system health.",
    skills: ["Windows Server & Active Directory", "Linux boshqaruvi", "Zaxiralash tizimlari", "Apparat ta'minoti"],
    subjects: ["Informatika", "Fizika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Apparat & OS", items: ["Kompyuter qismlari", "Windows/Linux o'rnatish", "Lokal tarmoq ulash"] },
      stage2: { period: "3–6 oy", title: "Server boshqaruvi", items: ["Active Directory", "Fayl serverlari", "Guruh siyosatlari (GPO)"] },
      stage3: { period: "6–12 oy", title: "Linux & Virtualizatsiya", items: ["VMware / Proxmox", "Bash scriptlar", "Zaxira nusxalar olish"] },
      stage4: { period: "1–2 yil", title: "Avtomatlashtirish", items: ["Ansible", "Cloud infratuzilma", "Yuqori darajali xavfsizlik"] }
    },
    educationPath: "Axborot texnologiyalari kollejlari, TATU",
    futureOutlook: "Har bir davlat idorasi, shifoxona, maktab va xususiy kompaniyada o‘rni bor.",
    relatedCareers: ["Network Engineer", "DevOps Engineer", "Cybersecurity Specialist"],
    weightTech: 88,
    weightMed: 0,
    weightEng: 50,
    weightSoc: 15,
    weightCre: 10,
    weightBus: 25,
    weightNat: 0,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-tech-15",
    slug: "product-manager",
    nameUz: "Mahsulot Menejeri (IT Product Manager)",
    nameKrill: "Маҳсулот Менежери (IT Product Manager)",
    nameRu: "Продуктовый менеджер (Product Manager)",
    nameEn: "IT Product Manager",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Raqamli mahsulot (ilova, sayt yoki xizmat) g‘oyasidan tortib uning bozorga chiqishi, dizayni va foydalanuvchilar ehtiyojini boshqaruvchi yetakchi.",
    descriptionKrill: "Рақамли маҳсулот (илова, сайт ёки хизмат) ғоясидан тортиб унинг бозорга чиқиши, дизайни ва фойдаланувчилар эҳтиёжини бошқарувчи етакчи.",
    descriptionRu: "Определяет стратегию цифрового продукта, координирует работу дизайнеров и программистов ради успеха на рынке.",
    descriptionEn: "Guides digital product strategy, discovery, roadmap prioritization, and business metrics delivery.",
    skills: ["Mahsulot strategiyasi", "Scrum / Agile", "Bozor tahlili", "Muloqot va yetakchilik", "UX tushunchasi"],
    subjects: ["Iqtisodiyot", "Ingliz tili", "Informatika", "Ona tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Mahsulot asoslari", items: ["Customer Development", "Bozor tahlili", "Foydalanuvchi tadqiqoti"] },
      stage2: { period: "3–6 oy", title: "Metrikalar & Metodologiya", items: ["Agile/Scrum", "LTV, CAC, Retention metrikalari", "Jira & Confluence"] },
      stage3: { period: "6–12 oy", title: "Prototip va Roadmap", items: ["Figma prototiplari", "PRD hujjati tuzish", "A/B gipotezalari"] },
      stage4: { period: "1–2 yil", title: "Bozorga chiqarish (GTM)", items: ["Monetizatsiya modellari", "Jamoa yetakchiligi", "Unit-iqtisodiyot"] }
    },
    educationPath: "TDIU, Jahon iqtisodiyoti va diplomatiya universiteti (JIDU), TATU",
    futureOutlook: "Raqamli startaplar va xalqaro korporatsiyalarda eng yuqori maoshli yetakchilik roli.",
    relatedCareers: ["UI/UX Designer", "Data Analyst", "Entrepreneur"],
    weightTech: 75,
    weightMed: 0,
    weightEng: 20,
    weightSoc: 65,
    weightCre: 60,
    weightBus: 95,
    weightNat: 0,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-tech-16",
    slug: "robotics-engineer",
    nameUz: "Robototexnika Muhandisi",
    nameKrill: "Робототехника Муҳандиси",
    nameRu: "Инженер-робототехник",
    nameEn: "Robotics Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Sanoat robotlari, avtonom dronlar va aqlli manipulyatorlarning mexanikasini yasovchi va ularga dasturiy aql beruvchi muhandis.",
    descriptionKrill: "Саноат роботлари, автоном дронлар ва ақлли манипуляторларнинг механикасини ясовчи ва уларга дастурий ақл берувчи муҳандис.",
    descriptionRu: "Проектирует механические конструкции роботов, микроконтроллерные платы и программирует их поведение.",
    descriptionEn: "Designs automated robotic systems, sensor integration, microcontroller boards, and motion logic.",
    skills: ["C++ / Python", "Arduino & STM32", "ROS (Robot Operating System)", "3D modellashtirish", "Elektronika"],
    subjects: ["Fizika", "Matematika", "Informatika", "Chizmachilik"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Elektronika & Arduino", items: ["Ohm qonuni, datchiklar", "Arduino dasturlash", "Dvigatellar boshqaruvi"] },
      stage2: { period: "3–6 oy", title: "Mexanika & 3D", items: ["SolidWorks / Fusion 360", "3D printerda chop etish", "STM32 mikrokontrolleri"] },
      stage3: { period: "6–12 oy", title: "ROS & Kinematika", items: ["Robot kinematikasi", "ROS 2 asoslari", "LIDAR va navigatsiya"] },
      stage4: { period: "1–2 yil", title: "Sun'iy ong integratsiyasi", items: ["Computer Vision (OpenCV)", "Avtonom harakatlanish", "Sanoat robotlari"] }
    },
    educationPath: "Toshkent Davlat Texnika Universiteti (TDTU), Turin Politexnika Universiteti",
    futureOutlook: "Zavodlar, qishloq xo‘jaligi va tibbiyotda avtomatlashtirish robotlariga ehtiyoj mislsiz oshmoqda.",
    relatedCareers: ["Embedded Developer", "AI Engineer", "Automotive Engineer"],
    weightTech: 92,
    weightMed: 10,
    weightEng: 100,
    weightSoc: 10,
    weightCre: 55,
    weightBus: 25,
    weightNat: 0,
    weightLaw: 5,
    active: true
  },
  {
    id: "car-tech-17",
    slug: "embedded-developer",
    nameUz: "O‘rnatilgan Tizimlar Dasturchisi (Embedded Dev)",
    nameKrill: "Ўрнатилган Тизимлар Дастурчиси (Embedded Dev)",
    nameRu: "Разработчик встроенных систем (Embedded Dev)",
    nameEn: "Embedded Systems Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Avtomobillar, maishiy texnika, tibbiy apparatlar va mikrokontrollerlarga bevosita apparat darajasida kod yozuvchi muhandis.",
    descriptionKrill: "Автомобиллар, маиший техника, тиббий аппаратлар ва микроконтроллерларга бевосита аппарат даражасида код ёзувчи муҳандис.",
    descriptionRu: "Пишет низкоуровневый код на Си/C++ для процессоров, чипов, датчиков и умных устройств.",
    descriptionEn: "Writes low-level firmware in C/C++ running directly on microcontrollers, hardware sensors, and smart gadgets.",
    skills: ["C / C++", "RTOS (Real-time OS)", "Mikrokontrollerlar (ARM / ESP32)", "Protokollar (I2C, SPI, UART)"],
    subjects: ["Fizika", "Informatika", "Matematika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "C tili chuqur", items: ["Ko'rsatkichlar (Pointers)", "Xotira boshqaruvi", "Bitwise amallar"] },
      stage2: { period: "3–6 oy", title: "Mikrokontroller", items: ["ESP32 va STM32", "Registerlar bilan ishlash", "Datchiklar integratsiyasi"] },
      stage3: { period: "6–12 oy", title: "RTOS & IoT", items: ["FreeRTOS", "Bluetooth & Wi-Fi modullar", "Kam quvvatli rejimlar"] },
      stage4: { period: "1–2 yil", title: "Pro daraja", items: ["Apparat drayverlari", "Avtomobil CAN-shinalari", "Firmware yangilash (OTA)"] }
    },
    educationPath: "TDTU, Turin Politexnika, TATU",
    futureOutlook: "Smart-home, elektromobillar va tibbiy texnikalar ishlab chiqarishida juda zarur mutaxassis.",
    relatedCareers: ["Robotics Engineer", "Automotive Electronics Specialist", "Network Engineer"],
    weightTech: 95,
    weightMed: 5,
    weightEng: 85,
    weightSoc: 5,
    weightCre: 30,
    weightBus: 20,
    weightNat: 0,
    weightLaw: 5,
    active: true
  }
];
