import { Career } from '../../src/types';

export const TECH_CAREERS: Career[] = [
  {
    id: "car-tech-1",
    slug: "software-developer",
    nameUz: "Dasturchi (Software Developer)",
    nameKrill: "Дастурчи (Software Developer)",
    nameRu: "Разработчик ПО (Software Developer)",
    nameEn: "Software Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Murakkab tizimlar, algoritmlar va kompyuter dasturlarini yaratuvchi, biznes va insoniyat muammolarini kod yordamida yechuvchi mutaxassis.",
    descriptionKrill: "Мураккаб тизимлар, алгоритмлар ва компьютер дастурларини яратувчи, бизнес ва инсоният муаммоларини код ёрдамида ечувчи мутахассис.",
    descriptionRu: "Специалист, создающий программное обеспечение, алгоритмы и сервисы для решения практических задач.",
    descriptionEn: "Builds robust software applications, backend architectures, and algorithmic systems to solve complex challenges.",
    skills: ["Python", "JavaScript / TypeScript", "Mantiqiy fikrlash", "Algoritmlar", "Git & GitHub"],
    subjects: ["Informatika", "Matematika", "Ingliz tili", "Fizika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Asoslar va Mantiq", items: ["Kompyuter arxitekturasi", "Typing (tez yozish)", "Ingliz tili A2/B1", "Algoritmik mantiq"] },
      stage2: { period: "3–6 oy", title: "Dasturlash tili", items: ["Python yoki JavaScript asoslari", "Ma'lumotlar tuzilmalari", "OOP tamoyillari"] },
      stage3: { period: "6–12 oy", title: "Loyihalar va DB", items: ["SQL va NoSQL ma'lumotlar bazasi", "Git bilan ishlash", "Kichik mustaqil loyihalar"] },
      stage4: { period: "1–2 yil", title: "Professional daraja", items: ["Arxitektura va API", "Docker va Cloud", "Jamoaviy dasturlash"] }
    },
    educationPath: "TATU, Inha, Amity, Astrum yoki Raqamli Texnologiyalar OTMlari",
    futureOutlook: "Dunyo va O‘zbekiston bozorida talab juda yuqori, oylik maosh istiqboli yuqori.",
    relatedCareers: ["Full Stack Developer", "Backend Developer", "AI Engineer"],
    weightTech: 100,
    weightMed: 0,
    weightEng: 35,
    weightSoc: 15,
    weightCre: 45,
    weightBus: 25,
    weightNat: 0,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-tech-2",
    slug: "frontend-developer",
    nameUz: "Frontend Dasturchi",
    nameKrill: "Frontend Дастурчи",
    nameRu: "Frontend Разработчик",
    nameEn: "Frontend Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Veb-sayt va ilovalarning foydalanuvchi ko‘radigan, tugmalar bosiladigan interfeys qismini yaratuvchi dasturchi.",
    descriptionKrill: "Веб-сайт ва иловаларнинг фойдаланувчи кўрадиган, тугмалар босиладиган интерфейс қисмини яратувчи дастурчи.",
    descriptionRu: "Разрабатывает пользовательские интерфейсы веб-сайтов и приложений, уделяя внимание эстетике и адаптивности.",
    descriptionEn: "Builds client-side user interfaces, interactive components, and responsive web experiences.",
    skills: ["HTML5 & CSS3", "JavaScript / TypeScript", "React / Vue", "Tailwind CSS"],
    subjects: ["Informatika", "Tasviriy san'at", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Web asoslari", items: ["HTML semantikasi", "CSS flexbox & grid", "Responsive dizayn"] },
      stage2: { period: "3–6 oy", title: "JavaScript", items: ["JS asoslari va DOM", "Asinxron JS (Fetch/API)", "TypeScript asoslari"] },
      stage3: { period: "6–12 oy", title: "Zamonaviy Framework", items: ["React va Next.js", "State management", "Portfolio loyihalari"] },
      stage4: { period: "1–2 yil", title: "Senior darajaga o'tish", items: ["Performance optimallash", "Testing (Jest)", "Microfrontends"] }
    },
    educationPath: "Axborot texnologiyalari fakultetlari, IT Park akademiyalari",
    futureOutlook: "Har bir biznes va startap uchun doimiy kerak bo‘ladigan yo‘nalish.",
    relatedCareers: ["UI/UX Designer", "Full Stack Developer", "Web Developer"],
    weightTech: 92,
    weightMed: 0,
    weightEng: 20,
    weightSoc: 25,
    weightCre: 85,
    weightBus: 20,
    weightNat: 0,
    weightLaw: 5,
    active: true
  },
  {
    id: "car-tech-3",
    slug: "backend-developer",
    nameUz: "Backend Dasturchi",
    nameKrill: "Backend Дастурчи",
    nameRu: "Backend Разработчик",
    nameEn: "Backend Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Serverlar, ma'lumotlar bazasi va biznes mantig‘i xavfsiz va uzluksiz ishlashini ta'minlovchi muhandis.",
    descriptionKrill: "Серверлар, маълумотлар базаси ва бизнес мантиғи хавфсиз ва узлуксиз ишлашини таъминловчи муҳандис.",
    descriptionRu: "Создает серверную логику, API и базы данных, обеспечивая высокую производительность и безопасность.",
    descriptionEn: "Architects server engines, data pipelines, and APIs powering digital infrastructure.",
    skills: ["Node.js / Go / Python", "PostgreSQL / Redis", "REST & GraphQL", "Docker"],
    subjects: ["Informatika", "Matematika", "Fizika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Til va Terminal", items: ["Linux buyruqlari", "Asosiy til sintaksisi", "Mantiqiy amallar"] },
      stage2: { period: "3–6 oy", title: "API & DB", items: ["Express / FastAPI", "PostgreSQL CRUD", "Autentifikatsiya (JWT)"] },
      stage3: { period: "6–12 oy", title: "Arxitektura", items: ["Caching (Redis)", "Microservice tushunchasi", "CI/CD pipeline"] },
      stage4: { period: "1–2 yil", title: "Masshtablash", items: ["Highload optimizatsiya", "Kafqa / RabbitMQ", "Cloud infratuzilma"] }
    },
    educationPath: "TATU, Toshkent Davlat Texnika Universiteti, Amity",
    futureOutlook: "Banklar, to‘lov tizimlari va xalqaro korporatsiyalarda eng qimmatli mutaxassislar.",
    relatedCareers: ["Software Developer", "DevOps Engineer", "Database Engineer"],
    weightTech: 96,
    weightMed: 0,
    weightEng: 40,
    weightSoc: 10,
    weightCre: 25,
    weightBus: 30,
    weightNat: 0,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-tech-4",
    slug: "ai-engineer",
    nameUz: "Sun'iy Intellekt (AI) Muhandisi",
    nameKrill: "Сунъий Интеллект (AI) Муҳандиси",
    nameRu: "Инженер Искусственного Интеллекта",
    nameEn: "Artificial Intelligence (AI) Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Neyrotarmoqlar, kompyuter ko‘rishi, LLM va mashinali o‘rganish modellarini yaratuvchi zamonaviy IT kashfiyotchisi.",
    descriptionKrill: "Нейротармоқлар, компьютер кўриши, LLM ва машинали ўрганиш моделларини яратувчи замонавий IT кашфиётчиси.",
    descriptionRu: "Разрабатывает нейросети, языковые модели (LLM) и алгоритмы машинного обучения для автоматизации процессов.",
    descriptionEn: "Builds generative neural models, computer vision systems, and autonomous intelligent workflows.",
    skills: ["Python", "TensorFlow / PyTorch", "Matematik statistika", "LLM Fine-tuning", "NLP"],
    subjects: ["Matematika (Oliy algebra)", "Informatika", "Ingliz tili", "Fizika"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Matematika & Python", items: ["Chiziqli algebra", "Ehtimollar nazariyasi", "NumPy & Pandas"] },
      stage2: { period: "3–6 oy", title: "Mashinali o'rganish", items: ["Scikit-Learn", "Regressiya va Klassifikatsiya", "Data Visualization"] },
      stage3: { period: "6–12 oy", title: "Chuqur o'rganish", items: ["Neural Networks", "PyTorch asoslari", "Vision / NLP modellari"] },
      stage4: { period: "1–2 yil", title: "Generative AI", items: ["Transformer arxitekturasi", "Prompt Engineering & RAG", "Model Deployment"] }
    },
    educationPath: "TATU AI fakulteti, New Uzbekistan University, Akfa/Central Asian University",
    futureOutlook: "Kelgusi 20 yillikning eng jadal o‘suvchi va strategik ahamiyatga ega kasbi.",
    relatedCareers: ["Data Scientist", "Machine Learning Engineer", "Robotics Engineer"],
    weightTech: 100,
    weightMed: 15,
    weightEng: 60,
    weightSoc: 20,
    weightCre: 50,
    weightBus: 40,
    weightNat: 10,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-tech-5",
    slug: "cybersecurity-specialist",
    nameUz: "Kiberxavfsizlik Mutaxassisi",
    nameKrill: "Киберхавфсизлик Мутахассиси",
    nameRu: "Специалист по кибербезопасности",
    nameEn: "Cybersecurity Specialist",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Davlat va kompaniya tarmoqlarini hakerlar hujumidan, ma'lumotlar sizib chiqishidan himoya qiluvchi raqamli posbon.",
    descriptionKrill: "Давлат ва компания тармоқларини ҳакерлар ҳужумидан, маълумотлар сизиб чиқишидан ҳимоя қилувчи рақамли посбон.",
    descriptionRu: "Защищает критические серверы, базы данных и сетевые системы от кибератак и утечек информации.",
    descriptionEn: "Guards network infrastructures, performs penetration testing, and detects vulnerabilities against threats.",
    skills: ["Tarmoq protokollari (TCP/IP)", "Linux xavfsizligi", "Penetration Testing", "Kriptografiya", "Wireshark"],
    subjects: ["Informatika", "Matematika", "Huquq", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Tarmoq asoslari", items: ["OSI modeli va TCP/IP", "Linux buyruqlar satri", "Kriptografiya asoslari"] },
      stage2: { period: "3–6 oy", title: "Xavfsizlik vositalari", items: ["Nmap, Wireshark", "Web zaifliklar (OWASP Top 10)", "Python for Security"] },
      stage3: { period: "6–12 oy", title: "Amaliy himoya", items: ["Ethical Hacking", "SIEM tizimlari", "Incident response"] },
      stage4: { period: "1–2 yil", title: "Sertifikatlar", items: ["CompTIA Security+", "CEH yoki OSCP tayyorgarlik", "Red/Blue Teaming"] }
    },
    educationPath: "Jamoat xavfsizligi universiteti, TATU Kiberxavfsizlik fakulteti",
    futureOutlook: "Harbiy, bank va davlat xavfsizligi sohalarida eng nufuzli kasb.",
    relatedCareers: ["System Administrator", "Network Engineer", "DevOps Engineer"],
    weightTech: 94,
    weightMed: 0,
    weightEng: 40,
    weightSoc: 10,
    weightCre: 15,
    weightBus: 30,
    weightNat: 0,
    weightLaw: 85,
    active: true
  },
  {
    id: "car-tech-6",
    slug: "mobile-developer",
    nameUz: "Mobil Ilovalar Dasturchisi (iOS / Android)",
    nameKrill: "Мобил Иловалар Дастурчиси (iOS / Android)",
    nameRu: "Мобильный разработчик (iOS / Android)",
    nameEn: "Mobile App Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Smartfonlar uchun qulay, chiroyli va tez ishlaydigan mobil ilovalarni yaratuvchi dasturchi.",
    descriptionKrill: "Смартфонлар учун қулай, чиройли ва тез ишлайдиган мобил иловаларни яратувчи дастурчи.",
    descriptionRu: "Создает функциональные и быстрые приложения для смартфонов под iOS и Android.",
    descriptionEn: "Develops native and cross-platform mobile apps delivering seamless portable user experiences.",
    skills: ["Flutter / React Native", "Kotlin / Swift", "Mobile UI Patterns", "REST API integratsiyasi"],
    subjects: ["Informatika", "Ingliz tili", "Tasviriy san'at"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Asosiy til", items: ["Dart yoki Kotlin sintaksisi", "OOP tushunchalari", "Git"] },
      stage2: { period: "3–6 oy", title: "Mobile UI", items: ["Vidjetlar daraxti", "State Management (Bloc/Provider)", "Navigatsiya"] },
      stage3: { period: "6–12 oy", title: "Backend ulanish", items: ["REST API / Firebase", "Lokal saqlash (Hive/Room)", "Push-bildirishnomalar"] },
      stage4: { period: "1–2 yil", title: "Nashr qilish", items: ["Google Play / App Store deploy", "App optimallashtirish", "Arxitektura (Clean/MVVM)"] }
    },
    educationPath: "TATU, Inha, IT-Park IT Akademiyasi",
    futureOutlook: "Dunyo aholisining 90% smartfonlardan foydalanadi, talab to‘xtovsiz o‘smoqda.",
    relatedCareers: ["Frontend Developer", "Game Developer", "UI/UX Designer"],
    weightTech: 92,
    weightMed: 0,
    weightEng: 25,
    weightSoc: 20,
    weightCre: 70,
    weightBus: 35,
    weightNat: 0,
    weightLaw: 10,
    active: true
  },
  {
    id: "car-tech-7",
    slug: "game-developer",
    nameUz: "O‘yin Dasturchisi (Game Developer)",
    nameKrill: "Ўйин Дастурчиси (Game Developer)",
    nameRu: "Разработчик игр (Game Developer)",
    nameEn: "Game Developer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Kompyuter va mobil o‘yinlarning o‘yin mexanikasi, fizikasi, 3D olami va syujetini dasturlashtiruvchi ijodiy muhandis.",
    descriptionKrill: "Компьютер ва мобил ўйинларнинг ўйин механикаси, физикаси, 3D олами ва сюжетини дастурлаштирувчи ижодий муҳандис.",
    descriptionRu: "Создает физику, логику и графику компьютерных и мобильных игр на движках Unity или Unreal Engine.",
    descriptionEn: "Programs gameplay loops, physics simulations, 3D graphics, and narrative video games.",
    skills: ["Unity / C#", "Unreal Engine / C++", "3D Matematika & Fizika", "Game Design"],
    subjects: ["Fizika", "Matematika (Geometriya)", "Informatika", "Tasviriy san'at"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "O'yin dvijogi", items: ["Unity interfeysi", "C# asoslari", "2D fizika va harakat"] },
      stage2: { period: "3–6 oy", title: "3D olam", items: ["3D koordinatalar", "Yoritish va materiallar", "Ovoz effektlari"] },
      stage3: { period: "6–12 oy", title: "Game Loop", items: ["O'yin mexanikasi", "UI & Menu tizimlari", "Kichik demo o'yin"] },
      stage4: { period: "1–2 yil", title: "Multiplayer", items: ["Tarmoq arxitekturasi", "Shaders va optimizatsiya", "Steam / itch.io nashr"] }
    },
    educationPath: "TATU Multimedia texnologiyalari fakulteti, xalqaro GameDev kurslari",
    futureOutlook: "Global o‘yin bozori kinodan 3 baravar katta aylanmaga ega.",
    relatedCareers: ["3D Animator", "Software Developer", "UI/UX Designer"],
    weightTech: 93,
    weightMed: 0,
    weightEng: 40,
    weightSoc: 15,
    weightCre: 95,
    weightBus: 25,
    weightNat: 0,
    weightLaw: 5,
    active: true
  },
  {
    id: "car-tech-8",
    slug: "data-analyst",
    nameUz: "Ma'lumotlar Tahlilchisi (Data Analyst)",
    nameKrill: "Маълумотлар Таҳлилчиси (Data Analyst)",
    nameRu: "Аналитик данных (Data Analyst)",
    nameEn: "Data Analyst",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Raqamlar, sotuvlar va statistik ma'lumotlarni tahlil qilib, rahbarlarga to‘g‘ri biznes qarorlar qabul qilishga ko‘maklashadi.",
    descriptionKrill: "Рақамлар, сотувлар ва статистик маълумотларни таҳлил қилиб, раҳбарларга тўғри бизнес қарорлар қабул қилишга кўмаклашади.",
    descriptionRu: "Собирает, очищает и визуализирует массивы данных, превращая цифры в стратегические бизнес-выводы.",
    descriptionEn: "Transforms raw numbers and metrics into dashboards, actionable insights, and business intelligence.",
    skills: ["SQL", "Excel (Professional)", "Power BI / Tableau", "Python (Pandas)"],
    subjects: ["Matematika", "Iqtisodiyot", "Informatika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Excel & Statistika", items: ["Pivot tables", "VLOOKUP / XLOOKUP", "Deskriptiv statistika"] },
      stage2: { period: "3–6 oy", title: "SQL & Ma'lumotlar", items: ["SQL SELECT, JOIN, GROUP BY", "Ma'lumotlarni tozalash", "Relyatsion modellar"] },
      stage3: { period: "6–12 oy", title: "BI Dashboards", items: ["Power BI hisobotlari", "DAX formulalari", "Biznes metrikalari"] },
      stage4: { period: "1–2 yil", title: "Python tahlili", items: ["Pandas, Matplotlib, Seaborn", "A/B testlar", "Bashoratli tahlil"] }
    },
    educationPath: "Toshkent Davlat Iqtisodiyot Universiteti (TDIU), TATU, Inha",
    futureOutlook: "Har bir bank, supermarket tarmog‘i va korxona uchun strategik mutaxassis.",
    relatedCareers: ["Data Scientist", "Business Consultant", "Accountant"],
    weightTech: 85,
    weightMed: 0,
    weightEng: 20,
    weightSoc: 30,
    weightCre: 25,
    weightBus: 90,
    weightNat: 0,
    weightLaw: 20,
    active: true
  },
  {
    id: "car-tech-9",
    slug: "devops-engineer",
    nameUz: "DevOps Muhandisi",
    nameKrill: "DevOps Муҳандиси",
    nameRu: "DevOps-инженер",
    nameEn: "DevOps Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Dasturchilar yozgan kodni avtomatik sinovdan o‘tkazib, serverlarga xatosiz va uzluksiz yetkazib berish tizimini quruvchi mutaxassis.",
    descriptionKrill: "Дастурчилар ёзган кодни автоматик синовдан ўтказиб, серверларга хатосиз ва узлуксиз етказиб бериш тизимини қурувчи мутахассис.",
    descriptionRu: "Настраивает автоматизацию сборки, тестирования и развертывания приложений в облачной инфраструктуре.",
    descriptionEn: "Bridges software development and operations through automated CI/CD pipelines, Docker, and Kubernetes.",
    skills: ["Linux", "Docker & Kubernetes", "CI/CD (GitLab, GitHub Actions)", "AWS / Google Cloud"],
    subjects: ["Informatika", "Fizika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "Linux & Tarmoq", items: ["Bash scripting", "SSH va xavfsizlik", "DNS, HTTP, Firewall"] },
      stage2: { period: "3–6 oy", title: "Konteynerlar", items: ["Docker arxitekturasi", "Docker Compose", "Git flows"] },
      stage3: { period: "6–12 oy", title: "CI/CD & Cloud", items: ["GitHub Actions", "Terraform asoslari", "AWS/Cloudflare"] },
      stage4: { period: "1–2 yil", title: "Orkestratsiya", items: ["Kubernetes (k8s)", "Monitoring (Prometheus/Grafana)", "Site Reliability (SRE)"] }
    },
    educationPath: "TATU, TDTU, xalqaro bulutli sertifikatlar (AWS Certified)",
    futureOutlook: "IT sohasida eng kamyob va yuqori daromadli muhandislar safida.",
    relatedCareers: ["Cloud Engineer", "System Administrator", "Backend Developer"],
    weightTech: 98,
    weightMed: 0,
    weightEng: 50,
    weightSoc: 10,
    weightCre: 20,
    weightBus: 35,
    weightNat: 0,
    weightLaw: 25,
    active: true
  },
  {
    id: "car-tech-10",
    slug: "database-engineer",
    nameUz: "Ma'lumotlar Bazasi Muhandisi (DBA)",
    nameKrill: "Маълумотлар Базаси Муҳандиси (DBA)",
    nameRu: "Инженер баз данных (DBA)",
    nameEn: "Database Administrator / Engineer",
    category: "Technology",
    imageUrl: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?q=80&w=1200&auto=format&fit=crop",
    descriptionUz: "Millionlab insonlar ma'lumotlarini tezkor, xavfsiz va zaxira nusxalari bilan saqlovchi ma'lumotlar bazasi me'mori.",
    descriptionKrill: "Миллионлаб инсонлар маълумотларини тезкор, хавфсиз ва захира нусхалари билан сақловчи маълумотлар базаси меъмори.",
    descriptionRu: "Проектирует высоконадежные базы данных, оптимизирует тяжелые запросы и обеспечивает отказоустойчивость.",
    descriptionEn: "Designs enterprise relational and distributed databases, query optimization, and disaster recovery.",
    skills: ["PostgreSQL / Oracle / MySQL", "Query Optimization", "Replikatsiya & Sharding", "Zaxiralash (Backup)"],
    subjects: ["Informatika", "Matematika", "Ingliz tili"],
    learningPath: {
      stage1: { period: "0–3 oy", title: "SQL chuqur", items: ["Murakkab JOINlar", "Indekslar", "Tranzaksiyalar (ACID)"] },
      stage2: { period: "3–6 oy", title: "DB Administrator", items: ["User huquqlari", "Backup va Restore", "Monitoring"] },
      stage3: { period: "6–12 oy", title: "Optimizatsiya", items: ["EXPLAIN ANALYZE", "Partitioning", "Connection Pooling"] },
      stage4: { period: "1–2 yil", title: "Tarqalgan DB", items: ["High Availability", "MongoDB/Cassandra", "Cloud Databases"] }
    },
    educationPath: "TATU, Toshkent Axborot Texnologiyalari OTMlari",
    futureOutlook: "Banklar va davlat elektron xizmatlari uchun muhim poydevor kasbi.",
    relatedCareers: ["Backend Developer", "DevOps Engineer", "Data Analyst"],
    weightTech: 93,
    weightMed: 0,
    weightEng: 35,
    weightSoc: 5,
    weightCre: 10,
    weightBus: 40,
    weightNat: 0,
    weightLaw: 30,
    active: true
  }
];
